;;; helixel-textobj-pair.el --- Paren / quote / xml-tag text objects -*- lexical-binding: t; -*-

;; Copyright (C) 2026  jixiuf

;; Author: jixiuf <https://github.com/jixiuf>
;; Keywords: convenience
;; URL: https://github.com/jixiuf/helixel-mode
;; SPDX-License-Identifier: GPL-3.0-or-later

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;;; Commentary:
;;
;; This module hosts the delimiter protocol shared by text objects,
;; surround, and pair/match movements: the `helixel-delimiter' struct,
;; `helixel-delimiter-bounds', and the `helixel--generic-bounds-next' /
;; `-previous' navigation primitives.
;;
;; Plus the three "matched-pair" text-object families that share the
;; "find inner pair → return helixel-range" shape:
;;
;;   paren / bracket / brace / angle  (helixel-select-paren, helixel-up-paren)
;;   quote (single / double / back / etc.)  (helixel-select-quote,
;;                                            helixel-forward-quote)
;;   xml / sgml tag  (helixel-select-xml-tag, helixel-up-xml-tag)
;;
;; Plus the shared inner-bound helper `helixel-select-block' and the
;; delimiter constructors `helixel-make-pair-delimiter' and
;; `helixel-make-tag-delimiter'.
;;
;; Depends on engine (helixel-range, helixel-with-restriction,
;; helixel-motion-loop, helixel-textobj-visual-state-p-function).

;;; Code:

(require 'cl-lib)
(require 'helixel-textobj-engine)
(declare-function helixel-up-block-at-point "helixel-textobj-block" (&optional count))
(declare-function helixel--block-adjust-for-jump "helixel-textobj-block" ())
(declare-function helixel-up-regex-block "helixel-textobj-block"
                  (begin-re end-re &optional count name-group))
(declare-function helixel--regex-adjust-for-jump "helixel-textobj-block"
                  (begin-re end-re))
;; ----------------------------------------------------------------------
;; Delimiter Protocol
;; ----------------------------------------------------------------------
;;
;; A `helixel-delimiter' struct describes a delimited region (pair of
;; brackets, a quoted string, XML tags, mode-specific blocks, or
;; regex-defined blocks).  It carries enough information for both
;; text-object selection and surround add/delete/replace.
;;
;; Builder functions live in helixel-textobj-pair.el and
;; helixel-textobj-block.el (they reference textobj-engine functions
;; via closures).

(cl-defstruct (helixel-delimiter (:constructor helixel--make-delimiter-raw)
                                 (:copier nil))
  "Descriptor for a delimited region (pure data, no closures).
Slots shared by all delimiter types:
  TYPE           — :pair, :tag, or :regex.
  OPEN           — character or string; the opening delimiter.
  CLOSE          — character or string; the closing delimiter.
                   Unused (nil) for tag delimiters.
  MATCH-CLOSE    — function symbol (TAG-NAME) → 0, for tag delimiters
                   only.  Returns 0 on success, non-zero on failure.
                   Always nil for pair and block delimiters.
  BEGIN-RE       — string; regex for block opening delimiter.
                   Set only by `helixel-make-regex-delimiter'.
  END-RE         — string; regex for block closing delimiter.
  NAME-GROUP     — integer or nil; match group index for block name.

Finder and adjust-for-jump behavior is resolved from TYPE + slots by
`helixel-delimiter-find' / `helixel--delimiter-adjust-for-jump' —
delimiters hold no closures, so they stay printable and `equal'-able.
NL-P behaviour is derived from TYPE — tag and regex delimiters
handle adjacent newlines; pair delimiters do not."
  type
  open
  close
  match-close
  begin-re
  end-re
  name-group)

;; Generic accessors are auto-generated by `cl-defstruct' with
;; `:conc-name helixel-delimiter-':
;;   helixel-delimiter-type, helixel-delimiter-open,
;;   helixel-delimiter-close, helixel-delimiter-match-close,
;;   helixel-delimiter-begin-re, helixel-delimiter-end-re,
;;   helixel-delimiter-name-group.

(defsubst helixel-delimiter-nl-p (d)
  "Return non-nil if delimiter D uses newline handling.
Derived from TYPE — tag (:tag) and regex (:regex) delimiters
handle adjacent newlines; pair (:pair) delimiters do not."
  (memq (helixel-delimiter-type d) '(:tag :regex)))

;; ── Delimiter operations (stateless, no external deps) ──

(defvar-local helixel--block-chosen-spec nil
  "Internal: stores the spec chosen by block-finder at resolve time.
Set by block finder functions during `helixel-delimiter-bounds'.
Consumed by callers that need to know which block spec was matched.")

(defun helixel-delimiter-find (d dir)
  "Find delimiter D in DIR (+1 forward, -1 backward).
Returns 0 on success, non-zero on failure.  Moves point and sets `match-data'.
Dispatches on D's type, reading parameters from D's slots (pure data)."
  (let ((open (helixel-delimiter-open d))
        (close (helixel-delimiter-close d)))
    (pcase (helixel-delimiter-type d)
      (:pair (if (and open close (= open close))
                 (helixel--find-quote-pair open dir)
               (helixel-up-paren open close dir)))
      (:tag (helixel--tag-move-past-markup dir)
            (if (< dir 0)
                (helixel--tag-find-opener-backward)
              (helixel-up-xml-tag dir)))
      (:regex (if-let* ((begin-re (helixel-delimiter-begin-re d)))
                  (helixel-up-regex-block
                   begin-re (helixel-delimiter-end-re d) dir
                   (helixel-delimiter-name-group d))
                (helixel-up-block-at-point dir)))
      (_ (error "Unknown delimiter type: %s" (helixel-delimiter-type d))))))

(defun helixel--delimiter-adjust-for-jump (d)
  "Run the adjust-for-jump step for delimiter D, if any.
Dispatches on D's type, reading parameters from D's slots (pure data).
Quote pairs (open == close) need no adjustment."
  (let ((open (helixel-delimiter-open d))
        (close (helixel-delimiter-close d)))
    (pcase (helixel-delimiter-type d)
      (:pair (when (and open close (/= open close))
               (when (eq (char-after) open)
                 (forward-char))))
      (:tag (helixel--tag-adjust-for-jump))
      (:regex (if-let* ((begin-re (helixel-delimiter-begin-re d)))
                  (helixel--regex-adjust-for-jump
                   begin-re (helixel-delimiter-end-re d))
                (helixel--block-adjust-for-jump))))))

(defun helixel-delimiter-bounds (d &optional no-close-backoff)
  "Return ((OB . OE) . (CB . CE)) for the innermost delimiter D at point.
OB, OE: open delimiter beg/end.  CB, CE: close delimiter beg/end.
When NO-CLOSE-BACKOFF is non-nil, skip stepping back before a
closing delimiter.  Callers that just moved inside from the
opening delimiter (e.g. `helixel--generic-bounds-next' step 2)
should set this to avoid a false match for equal open/close chars."
  (let ((close (helixel-delimiter-close d)))
    (when (eobp) (skip-chars-backward " \t\n\r"))
    (when (and (not no-close-backoff)
               (characterp close) (> (point) 1)
               (= (char-before) close)
               (not (eq (char-after) close)))
      (backward-char))
    ;; String-based close backoff: if point is right after a string
    ;; close delimiter, step back to before it so the backward finder
    ;; can locate the opener without the close thwarting the counter.
    ;; Only apply when close differs from open (toggle-based delimiters
    ;; don't need backoff) and only when the matched close ends at point.
    (when (and (not no-close-backoff)
               (stringp close)
               (not (string= close (helixel-delimiter-open d))))
      (let ((orig (point)))
        (if (and (re-search-backward close nil t)
                 (= (match-end 0) orig))
            (goto-char (match-beginning 0))
          (goto-char orig))))
    (unwind-protect
        (progn
          (unless (zerop (helixel-delimiter-find d -1))
            (user-error "No enclosing delimiter"))
          (let ((ob (match-beginning 0)) (oe (match-end 0)))
            (goto-char oe)
            ;; For delimiters with a :match-close method (tags), use
            ;; targeted search so nested different-name pairs don't
            ;; steal the match.
            (if-let* ((mc (helixel-delimiter-match-close d))
                      (tag (match-string 1)))
                (funcall mc tag)
              (unless (zerop (helixel-delimiter-find d 1))
                (user-error "No enclosing delimiter")))
            (let ((cb (match-beginning 0)) (ce (match-end 0)))
              (cons (cons ob oe) (cons cb ce)))))
      (setq helixel--block-chosen-spec nil))))

(defsubst helixel-delimiter-bounds-flat (d &optional no-close-backoff)
  "Return (OB OE CB CE) for the innermost delimiter D at point.
OB, OE: open delimiter beg/end.  CB, CE: close delimiter beg/end.
Like `helixel-delimiter-bounds' but returns a flat list instead
of nested cons cells for easier destructuring.
Optional NO-CLOSE-BACKOFF is passed through to `helixel-delimiter-bounds'."
  (pcase-let* ((`((,ob . ,oe) . (,cb . ,ce))
                (helixel-delimiter-bounds d no-close-backoff)))
    (list ob oe cb ce)))

(defsubst helixel--generic-bounds-at (d &optional inner-p no-close-backoff)
  "Return (BEG . END) of enclosing delimiter D.
If INNER-P is non-nil, exclude delimiters from bounds.
When NO-CLOSE-BACKOFF is non-nil, skip the `backward-char' heuristic
in `helixel-delimiter-bounds' for the case where point is right
after the closing delimiter."
  (pcase-let* ((`(,ob ,oe ,cb ,ce)
                (helixel-delimiter-bounds-flat d no-close-backoff)))
    (if inner-p (cons oe cb) (cons ob ce))))

(defsubst helixel--strip-adjacent-newlines (open-end close-beg)
  "Adjust OPEN-END and CLOSE-BEG to exclude adjacent newlines.
Returns (OPEN-END . CLOSE-BEG)."
  (cons (if (eq (char-after open-end) ?\n) (1+ open-end) open-end)
        (if (eq (char-before close-beg) ?\n) (1- close-beg) close-beg)))

(defsubst helixel--delimiter-open-str (d)
  "Return the open delimiter of D as a string.
Converts character open to single-char string."
  (let ((open (helixel-delimiter-open d)))
    (and open (if (characterp open) (char-to-string open) open))))

(defun helixel--generic-bounds-just-exited-p (d orig-pt cur-bounds inner-p)
  "Return non-nil if we just exited an inner pair and landed on parent's cb.
Detects the case where adjacent closing delimiters like \=`))\='
would cause a false climb outward.  Only applies to outer-p
\(non-INNER-P) with character-type close delimiters.
D is the delimiter, ORIG-PT the starting point,
CUR-BOUNDS the current enclosing pair's bounds, INNER-P the inner flag."
  (and (not inner-p)
       (characterp (helixel-delimiter-close d))
       cur-bounds
       (let ((cb cur-bounds))
         (save-excursion
           (goto-char orig-pt)
           (catch 'helixel--just-exited
             (while (and (> (point) 1)
                         (= (char-before) (helixel-delimiter-close d)))
               (backward-char)
               (let ((bnds (save-excursion
                             (helixel--with-debug-log
                                 generic-bounds-next-just-exited
                               (helixel-delimiter-bounds-flat d)
                               (error nil)))))
                 (when (and bnds
                            (= orig-pt (nth 3 bnds))
                            (not (equal cb (cons (nth 0 bnds)
                                                 (nth 3 bnds)))))
                   (throw 'helixel--just-exited t))))
             nil)))))

(defun helixel--generic-bounds-next (d &optional inner-p)
  "Skip past current delimiter D, find next, return (BEG . END).
If INNER-P is non-nil, exclude delimiters from bounds.
If no next opening delimiter exists, falls back to the current
pair's bounds so callers can still move to that closing."
  (save-excursion
    (let* ((orig-pt (point))
           (cur-bounds (save-excursion
                         (helixel--with-debug-log generic-bounds-next
                           (helixel--generic-bounds-at d inner-p)
                           (error nil))))
           (open-str (helixel--delimiter-open-str d))
           (tag-p (eq (helixel-delimiter-type d) :tag))
           (just-exited (helixel--generic-bounds-just-exited-p
                         d orig-pt cur-bounds inner-p)))
      ;; Step 1: skip past current enclosing pair (or climb outward
      ;; if already at its closing edge).
      (when cur-bounds
        (setq cur-bounds
              (helixel--with-debug-log generic-bounds-next-step1
                (pcase-let* ((`(,_ob ,_oe ,cb ,ce)
                              (helixel-delimiter-bounds-flat d))
                             (at-closing
                              (and (>= orig-pt cb)
                                   (not just-exited))))
                  (if at-closing
                      (save-excursion
                        (goto-char ce)
                        (helixel--generic-bounds-at d inner-p t))
                    ;; NOT at-closing (or just-exited inner pair):
                    ;; go to the closer.
                    (goto-char ce)
                    cur-bounds))
                (error nil))))
      ;; Step 2: return enclosing pair's bounds, or search forward
      ;; for the first opening delimiter if not inside any pair.
      (or cur-bounds
          (when open-str
            (when (search-forward open-str nil t)
              (goto-char (1+ (match-beginning 0)))
              (when tag-p (search-forward ">" nil t))
              (helixel--generic-bounds-at d inner-p t)))))))

(defun helixel--generic-bounds-previous (d &optional inner-p)
  "Skip backward past current delimiter D, find previous opener.
If INNER-P is non-nil, return inner bounds (open-end . close-begin).
Otherwise return outer bounds (open-begin . close-end).
This is the backward mirror of `helixel--generic-bounds-next'.

Step 1: if inside a pair, go to its opener (ob for outer,
oe for inner).  If already at the opener, climb outward to the
parent pair's opener.

Step 2: if not inside any pair, search backward for the first
opening delimiter and return its bounds.

No `just-entered' check is needed (unlike `-next's `just-exited').
For backward direction, adjacent open chars like \=`((\=' have
ob(parent) < ob(child) always, so \=`(<= orig-pt ob)' is never
true when orig-pt sits at the child opener and bounds-at finds
the parent pair — the at-opening check correctly stays false.
For forward, the symmetric issue exists because cb(parent) can
equal ce(child) when \=`))\=' are adjacent."
  (save-excursion
    (let* ((orig-pt (point))
           (cur-bounds (save-excursion
                         (helixel--with-debug-log generic-bounds-previous
                           (helixel--generic-bounds-at d inner-p)
                           (error nil))))
           (open-str (helixel--delimiter-open-str d))
           (tag-p (eq (helixel-delimiter-type d) :tag)))
      ;; Step 1: skip backward to current enclosing pair's opener
      ;; (or climb outward if already at its opening edge).
      (when cur-bounds
        (setq cur-bounds
              (helixel--with-debug-log generic-bounds-previous-step1
                (pcase-let* ((`(,ob ,oe ,_cb ,_ce)
                              (helixel-delimiter-bounds-flat d))
                             (at-opening
                              (if inner-p
                                  (= orig-pt oe)
                                (<= orig-pt ob))))
                  (if at-opening
                      ;; Already at the opener: go to its beginning
                      ;; and re-find bounds — this finds the parent
                      ;; pair because at ob we haven't crossed the
                      ;; opener yet.
                      (save-excursion
                        (goto-char ob)
                        (helixel--generic-bounds-at d inner-p))
                    ;; NOT at opener: go to current pair's opener.
                    (goto-char (if inner-p oe ob))
                    cur-bounds))
                (error cur-bounds))))
      ;; Step 2: search backward for first opening delimiter
      ;; if not inside any pair.
      (or cur-bounds
          (when open-str
            (when (search-backward open-str nil t)
              (when tag-p (search-backward "<" nil t))
              (helixel--generic-bounds-at d inner-p t)))))))


;; ── Paren-or-quote inner-bound helpers ──

(defun helixel--get-block-range (op cl selection-type)
  "Return the exclusive range of a visual selection.
OP and CL are pairs of buffer positions for the opening and
closing delimiter of a range.  SELECTION-TYPE is the desired type
of selection.  It is a symbol that determines which parts of the
block are selected.  If it is `inclusive' or t the returned range
is \(cons (car OP) (cdr CL)).  If it is `exclusive' or nil the
returned range is (cons (cdr OP) (car CL)).  If it is
`exclusive-line' the returned range will skip whitespace at the
end of the line of OP and at the beginning of the line of CL."
  (cond
   ((memq selection-type '(inclusive t)) (cons (car op) (cdr cl)))
   ((memq selection-type '(exclusive nil)) (cons (cdr op) (car cl)))
   ((eq selection-type 'exclusive-line)
    (let ((beg (cdr op))
          (end (car cl)))
      (save-excursion
        (goto-char beg)
        (when (and (eolp) (not (eobp)))
          (setq beg (line-beginning-position 2)))
        (goto-char end)
        (skip-chars-backward " \t")
        (when (bolp)
          (setq end (point))
          (goto-char beg)
          (when (and (not (bolp)) (< beg end))
            (setq end (1- end)))))
      (cons beg end)))
   (t (user-error "Unknown selection-type `%s'" selection-type))))

;; ── Block-scan struct ──

(cl-defstruct (helixel--block-scan
               (:constructor helixel--make-block-scan)
               (:conc-name helixel--bs-)
               (:copier nil))
  "Result of a single scan attempt for a delimited block.
OP is a cons (BEG . END) of the opening delimiter, or nil.
CL is a cons (BEG . END) of the closing delimiter, or nil.
Both nil means the scan failed; both non-nil means success."
  (op nil :read-only t)
  (cl nil :read-only t))

(defun helixel--scan-forward-first (thing scan-pos fixedscan)
  "Scan1: from SCAN-POS forward to find the closer, then backward to opener.
THING is the finder function (see `helixel-up-block').
When FIXEDSCAN is nil, scan starts at (1+ SCAN-POS); otherwise at SCAN-POS.
Returns a `helixel--block-scan' on success, nil on failure.
Moves point and sets `match-data' as a side effect."
  (goto-char (if fixedscan scan-pos (1+ scan-pos)))
  (when (and (zerop (funcall thing +1)) (match-beginning 0))
    (let ((cl (cons (match-beginning 0) (match-end 0))))
      (goto-char (car cl))
      (if (and (zerop (funcall thing -1)) (match-beginning 0))
          (helixel--make-block-scan
           :op (cons (match-beginning 0) (match-end 0))
           :cl cl)
        nil))))

(defun helixel--scan-forward-closer (thing)
  "Find the forward closer for THING from point.
For tag delimiters with a `helixel--match-close' symbol property,
uses named-close matching so nested different-name pairs don't steal
the match.  For plain delimiters, calls (funcall thing +1).
Returns a cons (BEG . END) on success, nil on failure.
Side-effects: moves point, sets `match-data'."
  (let ((mc (and (symbolp thing)
                 (get thing 'helixel--match-close))))
    (if (and mc (match-string 1))
        (progn
          (funcall mc (match-string 1))
          (when (match-beginning 0)
            (cons (match-beginning 0) (match-end 0))))
      (when (and (zerop (funcall thing +1)) (match-beginning 0))
        (cons (match-beginning 0) (match-end 0))))))

(defun helixel--scan-backward-first (thing scan-pos fixedscan)
  "Scan2: from SCAN-POS backward to find the opener, then forward to closer.
THING is the finder function (see `helixel-up-block').
When FIXEDSCAN is nil, scan starts at (1- SCAN-POS); otherwise at SCAN-POS.
Returns a `helixel--block-scan' on success, nil on failure.
Moves point and sets `match-data' as a side effect."
  (goto-char (if fixedscan scan-pos (1- scan-pos)))
  (when (and (zerop (funcall thing -1)) (match-beginning 0))
    (let ((op (cons (match-beginning 0) (match-end 0))))
      (goto-char (cdr op))
      (let ((cl (helixel--scan-forward-closer thing)))
        (when cl
          (helixel--make-block-scan :op op :cl cl))))))

;; ── Scan resolution ──

(defun helixel--tag-names-match-p (op cl)
  "Return non-nil if OP and CL have matching XML tag names.
OP and CL are cons cells (BEG . END) of delimiter bounds.
When either is nil, returns nil."
  (and op cl
       (string= (helixel--xml-tag-name op)
                (helixel--xml-tag-name cl))))

(defun helixel--find-enclosing-pair (thing beg end &optional fixedscan
                                           orig-beg orig-end)
  "Find the enclosing pair around a region via dual-direction scan.
THING is a thing-fn (see `helixel-up-block').
BEG starts the forward-first scan (1+ shift unless FIXEDSCAN).
END starts the backward-first scan (1- shift unless FIXEDSCAN).
The two scans are resolved via `helixel--resolve-scans'.
Returns cons (OP . CL) on success, signals `user-error' on failure.
OP and CL are cons cells (BEG . END) of delimiter bounds."
  (let* ((scan1 (helixel--scan-forward-first thing beg fixedscan))
         (scan2 (helixel--scan-backward-first thing end fixedscan))
         (chosen (helixel--resolve-scans
                  scan1 scan2 beg orig-beg orig-end)))
    (unless (and chosen
                 (helixel--bs-op chosen)
                 (helixel--bs-cl chosen))
      (user-error "No surrounding delimiters found"))
    (cons (helixel--bs-op chosen)
          (helixel--bs-cl chosen))))

(defun helixel--resolve-scans (scan1 scan2 beg orig-beg orig-end)
  "Pick between SCAN1 and SCAN2, both `helixel--block-scan' or nil.
BEG is the start of the original region (or point).
ORIG-BEG, ORIG-END are the original caller-provided beg/end (may be nil).

Resolution rules, applied in order when both scans succeeded:
  1. Tightest containing: prefer the scan whose bounds tightly
     contain the original region (Bug #607).
  2. No-region at-opening: when there is no active region and scan1's
     opener starts at-or-after the scan position, prefer scan2 because
     scan1 found the next pair rather than the enclosing one.
  3. Tag mismatch: when scan1's opener/closer tag names don't match
     but scan2's do, prefer scan2.
Otherwise defaults to scan1.

Returns the chosen `helixel--block-scan', or nil when both are nil."
  (cond
   ((null scan1) scan2)
   ((null scan2) scan1)
   (t
    (let* ((s1-op (helixel--bs-op scan1)) (s1-cl (helixel--bs-cl scan1))
           (s2-op (helixel--bs-op scan2)) (s2-cl (helixel--bs-cl scan2)))
      (cond
       ;; Rule 1: tightest containing (Bug #607).
       ((and (>= (car s2-op) (car s1-op))
             (<= (cdr s2-cl) (cdr s1-cl))
             (<= (car s2-op) beg)
             (>= (cdr s2-cl) (or orig-end beg)))
        scan2)
       ;; Rule 2: no region, scan1 found next instead of enclosing.
       ((and (not orig-beg) (not orig-end)
             (>= (car s1-op) beg))
        scan2)
       ;; Rule 3: tag name mismatch in scan1, scan2 has a valid pair.
       ((and (not (helixel--tag-names-match-p s1-op s1-cl))
             (helixel--tag-names-match-p s2-op s2-cl))
        scan2)
       (t scan1))))))

;; ── Expand and build ──

(defun helixel--compute-expand-count (op cl count orig-beg orig-end
                                         selection-type countcurrent)
  "Return the number of levels remaining to expand outward.
OP and CL are the opener/closer bounds of the innermost pair.
COUNT is the absolute requested count.  ORIG-BEG/ORIG-END are the
caller-provided region bounds (may be nil).  SELECTION-TYPE determines
which parts of the block are selected (inclusive, exclusive, etc.).
When COUNTCURRENT is nil and the current selection already contains
the delimiters, count is NOT decremented (the current level does not
count as expansion)."
  (if (and orig-beg orig-end (not countcurrent))
      (let ((sel (helixel--get-block-range op cl selection-type)))
        (if (and (<= orig-beg (car sel))
                 (>= orig-end (cdr sel)))
            count
          (1- count)))
    (1- count)))

(defun helixel--expand-opener (thing op n)
  "Find the opener N levels outward from OP by calling THING.
Returns the new opener bounds or the original OP if not found."
  (goto-char (car op))
  (funcall thing n)
  (if (match-beginning 0)
      (cons (match-beginning 0) (match-end 0))
    op))

(defun helixel--expand-closer (thing cl n)
  "Find the closer N levels outward from CL by calling THING.
Returns the new closer bounds or the original CL if not found."
  (goto-char (cdr cl))
  (funcall thing n)
  (if (match-beginning 0)
      (cons (match-beginning 0) (match-end 0))
    cl))

(defun helixel--block-should-be-linewise-p (op cl type)
  "Return non-nil if the block from OP to CL should be linewise.
TYPE must be `inclusive', both OP and CL must be at bol,
and visual state must not be active."
  (save-excursion
    (and (not (and helixel-textobj-visual-state-p-function
                   (funcall helixel-textobj-visual-state-p-function)))
         (eq type 'inclusive)
         (progn (goto-char op) (bolp))
         (progn (goto-char cl) (bolp)))))

;; ── Main entry ──

(defun helixel-select-block (thing beg end type count
                                   &optional
                                   selection-type
                                   countcurrent
                                   fixedscan)
  "Return a range (BEG END) of COUNT delimited text objects.
BEG END TYPE are the currently selected (visual) range.  The
delimited object must be given by THING-up function (see
`helixel-up-block').

SELECTION-TYPE is symbol that determines which parts of the block
are selected.  If it is `inclusive' or t OPEN and CLOSE are
included in the range.  If it is `exclusive' or nil the delimiters
are not contained.  If it is `exclusive-line' the delimiters are
not included as well as adjacent whitespace until the beginning
of the next line or the end of the previous line.  If the
resulting selection consists of complete lines only and visual
state is not active, the returned selection is linewise.

If COUNTCURRENT is non-nil an objected is counted if the current
selection matches that object exactly.

Usually scanning for the surrounding block starts at (1+ beg)
and (1- end).  If this might fail due to the behavior of THING
then FIXEDSCAN can be set to t.  In this case the scan starts at
BEG and END.  One example where this might fail is if BEG and END
are the delimiters of a string or comment."
  (save-excursion
    (save-match-data
      (let* ((orig-beg beg)
             (orig-end end)
             (beg (or beg (point)))
             (end (or end (point)))
             (count (abs (or count 1))))
        ;; Ensure at least one selected character so scans don't
        ;; start and end at the same position when beg==end.
        (when (= beg end)
          (setq end (1+ end)))
        ;; Phase 1: dual-direction scan + resolve.
        (let* ((pair (helixel--find-enclosing-pair
                      thing beg end fixedscan orig-beg orig-end))
               (op (car pair))
               (cl (cdr pair))
               ;; Phase 3: compute how many levels to expand.
               (cnt (helixel--compute-expand-count
                     op cl count orig-beg orig-end
                     selection-type countcurrent)))
          ;; Special case: cursor outside the selected pair
          ;; (e.g. between </div> and </p>).  Expand one level
          ;; outward so the enclosing tag is found.
          (when (and (or (not orig-beg) (not orig-end))
                     (or (< beg (car op))
                         (> beg (cdr cl))))
            (setq cnt 1))
          ;; Phase 4: expand outward.
          (when (> cnt 0)
            (setq op (helixel--expand-opener thing op (- cnt))
                  cl (helixel--expand-closer thing cl cnt)))
          ;; Phase 5: compute final range.
          (let ((sel (helixel--get-block-range op cl selection-type)))
            (setq op (car sel)
                  cl (cdr sel)))
          (cond
           ((and (equal op orig-beg) (equal cl orig-end)
                 (or (not countcurrent) (/= count 1)))
            (user-error "No surrounding delimiters found"))
           ((helixel--block-should-be-linewise-p op cl type)
            (helixel-range op cl 'line :expanded t))
           (t (helixel-range op cl type :expanded t))))))))

;; ── Paren selection ──

(defun helixel-up-paren (open close &optional count)
  "Move point to the end or beginning of balanced parentheses.
OPEN and CLOSE should be characters identifying the opening and
closing parenthesis, respectively.  If COUNT is greater than zero
point is moved forward otherwise it is moved backwards.  Whenever
an opening delimiter is found the COUNT is increased by one, if a
closing delimiter is found the COUNT is decreased by one.  The
motion stops when COUNT reaches zero.  The `match-data' reflects the
last successful match (that caused COUNT to reach zero)."
  ;; Always use the default `forward-sexp-function'.  This is important
  ;; for modes that use a custom one like `python-mode'.
  ;; (addresses #364)
  (let (forward-sexp-function)
    (with-syntax-table (copy-syntax-table (syntax-table))
      (modify-syntax-entry open (format "(%c" close))
      (modify-syntax-entry close (format ")%c" open))
      (let ((rest (helixel-motion-loop (dir count)
                    (let ((pnt (point)))
                      (condition-case nil
                          (cond
                           ((> dir 0)
                            (while (progn
                                     (up-list dir t)
                                     (/= (char-before) close))))
                           (t
                            (while (progn
                                     (up-list dir t)
                                     (/= (char-after) open)))))
                        (error (goto-char pnt)))))))
        (cond
         ((= rest count) (set-match-data nil))
         ((> count 0) (set-match-data (list (1- (point)) (point))))
         (t (set-match-data (list (point) (1+ (point))))))
        rest))))

(defun helixel-select-paren (open close beg end type count &optional inclusive)
  "Return a range (BEG END) of COUNT delimited text objects.
OPEN and CLOSE are characters specifying the opening and closing
delimiters.  BEG END TYPE are the currently selected (visual)
range.  If INCLUSIVE is non-nil, OPEN and CLOSE are included in
the range; otherwise they are excluded.

If you aren't inside a pair of the opening and closing delimiters,
it jumps you inside the next one.  If there isn't one, it errors.

Uses `helixel-up-paren' with syntax-table awareness to handle
nesting and string/comment boundaries.

If the selection is exclusive, whitespace at the end or at the
beginning of the selection until the end-of-line or beginning-of-line
is ignored."
  (condition-case nil
      (progn
        ;; we need special linewise exclusive selection
        (unless inclusive (setq inclusive 'exclusive-line))
        (let ((thing (lambda (&optional cnt)
                       (helixel-up-paren open close cnt)))
              (bnd (or (bounds-of-thing-at-point 'helixel-string)
                       (bounds-of-thing-at-point 'helixel-comment)
                       ;; If point is at the opening quote of a string,
                       ;; this must be handled as if point is within the
                       ;; string, i.e. the selection must be extended
                       ;; around the string.  Otherwise
                       ;; `helixel-select-block' might do the wrong thing
                       ;; because it accidentally moves point inside the
                       ;; string (for inclusive selection) when looking
                       ;; for the current surrounding block. (re #364)
                       (and (= (point) (or beg (point)))
                            (save-excursion
                              (goto-char (1+ (or beg (point))))
                              (or (bounds-of-thing-at-point
                                   'helixel-string)
                                  (bounds-of-thing-at-point
                                   'helixel-comment)))))))
          (if (not bnd)
              (helixel-select-block thing beg end type count inclusive)
            (or (helixel-with-restriction (car bnd) (cdr bnd)
                  (ignore-errors
                    (helixel-select-block thing beg end type count
                                          inclusive)))
                (save-excursion
                  (setq beg (or beg (point))
                        end (or end (point)))
                  (goto-char (car bnd))
                  (let ((extbeg (min beg (car bnd)))
                        (extend (max end (cdr bnd))))
                    (helixel-select-block thing
                                          extbeg extend
                                          type
                                          count
                                          inclusive
                                          (or (< extbeg beg) (> extend end))
                                          t)))))))
    (error ; we aren't in the parens, so find next instance
     (save-match-data
       (goto-char (or (if (and count (> 0 count)) end beg)
                      (point)))
       (let ((re (regexp-quote (string open))))
         (if (and (not (looking-at-p re))
                  (re-search-forward re nil t count))
             (progn
               (goto-char (match-beginning 0))
               (let* ((mbeg (match-beginning 0))
                      (res (helixel-select-paren open close mbeg mbeg
                                                 type nil inclusive)))
                 (if (< (car res) mbeg)
                     ;; Error if found paren begins before target.
                     ;; Prevents g2ci( on `prova ( verder "((testo)")`
                     ;; from putting cursor inside deleted `()` after `prova`.
                     ;; Without this, it would go to the 2nd paren
                     ;; (the unbalanced one inside the quotes).
                     (user-error "No surrounding delimiters found")
                   res)))
           (user-error "No surrounding delimiters found")))))))

;; ── String / comment bounds helpers ──

(defun helixel--bounds-of-string-at-point (&optional state)
  "Return the bounds of a string at point.
If STATE is given it used a parsing state at point."
  (save-excursion
    (let ((state (or state (syntax-ppss))))
      (when (nth 3 state)
        (cons (nth 8 state)
              (when (parse-partial-sexp
                     (point) (point-max) nil nil state 'syntax-table)
                (point)))))))
(put 'helixel-string 'bounds-of-thing-at-point
     #'helixel--bounds-of-string-at-point)

(defun helixel--bounds-of-comment-at-point ()
  "Return the bounds of a comment at point."
  (save-excursion
    (let ((state (syntax-ppss)))
      (when (nth 4 state)
        (let ((beg (nth 8 state))
              (end (when (parse-partial-sexp
                          (point) (point-max) nil nil state 'syntax-table)
                     (point))))
          (when (and end (> end beg)
                     (eq (char-before end) ?\n))
            (setq end (1- end)))
          (cons beg end))))))
(put 'helixel-comment 'bounds-of-thing-at-point
     #'helixel--bounds-of-comment-at-point)

(defun helixel--forward-comment (count)
  "Move forward COUNT syntax comments.
COUNT positive: move to after the current/next comment end.
COUNT negative: move to before the current/previous comment start.

When already inside a comment, the first step moves to the far
end of that comment (cdr for forward, car for backward) before
looking for the next one.  Uses `syntax-ppss' to locate comment
boundaries."
  (let ((dir (if (> count 0) 1 -1)))
    (dotimes (_ (abs count))
      (if (nth 4 (syntax-ppss))
          ;; Already inside a comment — jump to the far end first.
          (when-let* ((bnd (helixel--bounds-of-comment-at-point)))
            (goto-char (if (> dir 0) (cdr bnd) (car bnd))))
        ;; Not in a comment — scan for the next opener.
        (let ((limit (if (> dir 0) (point-max) (point-min)))
              (found nil))
          (while (and (not found)
                      (if (> dir 0) (< (point) limit) (> (point) limit)))
            (forward-char dir)
            (setq found (nth 4 (syntax-ppss))))
          (if found
              (when-let* ((bnd (helixel--bounds-of-comment-at-point)))
                (goto-char (if (> dir 0) (cdr bnd) (car bnd))))
            ;; Reached buffer limit — position there.
            (goto-char (if (> dir 0) (point-max) (point-min)))))))))

(put 'helixel-comment 'forward-op #'helixel--forward-comment)



;; ── Quote selection ──

(defun helixel-forward-quote (quote &optional count)
  "Move point to the end or beginning of a string.
QUOTE is the character delimiting the string.  If COUNT is greater
than zero point is moved forward otherwise it is moved
backwards."
  (let (reset-parser)
    (with-syntax-table (copy-syntax-table (syntax-table))
      (unless (= (char-syntax quote) ?\")
        (modify-syntax-entry quote "\"")
        (syntax-ppss-flush-cache (point-min))
        (setq reset-parser t))
      ;; Ensure backslash has escape syntax (see
      ;; `helixel--bounds-of-quote-at-point').
      (unless (= (char-syntax ?\\) ?\\)
        (modify-syntax-entry ?\\ "\\")
        (syntax-ppss-flush-cache (point-min))
        (setq reset-parser t))
      ;; global parser state is out of state, use local one
      (let* ((pnt (point))
             (state (save-excursion
                      (beginning-of-defun)
                      (parse-partial-sexp (point) pnt nil nil (syntax-ppss))))
             (bnd (helixel--bounds-of-string-at-point state)))
        (when (and bnd (< (point) (cdr bnd)))
          ;; currently within a string
          (if (> count 0)
              (progn
                (goto-char (cdr bnd))
                (setq count (1- count)))
            (goto-char (car bnd))
            (setq count (1+ count))))
        ;; forward motions work with local parser state
        (cond
         ((> count 0)
          ;; no need to reset global parser state because we only use
          ;; the local one
          (setq reset-parser nil)
          (catch 'done
            (while (and (> count 0) (not (eobp)))
              (setq state (parse-partial-sexp
                           (point) (point-max) nil nil state 'syntax-table))
              (cond
               ((nth 3 state)
                (setq bnd (bounds-of-thing-at-point 'helixel-string))
                (goto-char (cdr bnd))
                (setq count (1- count)))
               ((eobp) (goto-char pnt) (throw 'done nil))))))
         ((< count 0)
          ;; need to update global cache because of backward motion
          (setq reset-parser (and reset-parser (point)))
          (save-excursion
            (beginning-of-defun)
            (syntax-ppss-flush-cache (point)))
          (catch 'done
            (while (and (< count 0) (not (bobp)))
              (setq pnt (point))
              (while (and (not (bobp))
                          (or (eobp) (/= (char-after) quote)))
                (backward-char))
              (cond
               ((setq bnd (bounds-of-thing-at-point 'helixel-string))
                (goto-char (car bnd))
                (setq count (1+ count)))
               ((bobp) (goto-char pnt) (throw 'done nil))
               (t (backward-char))))))
         (t (setq reset-parser nil)))))
    (when reset-parser
      ;; reset global cache
      (save-excursion
        (goto-char reset-parser)
        (beginning-of-defun)
        (syntax-ppss-flush-cache (point))))
    count))

(defvar helixel-forward-quote-char ?\"
  "The character to be used by `helixel--forward-quote-default'.")

(defun helixel--forward-quote (&optional count)
  "Move forward COUNT strings.
The quotation character is specified by the global variable
`helixel-forward-quote-char'.  This character is passed to
`helixel-forward-quote'."
  (helixel-forward-quote helixel-forward-quote-char count))
(defvar helixel--bounds-quote-char nil
  "Quote character for `helixel--bounds-of-quote-at-point'.")

(defun helixel--bounds-of-quote-at-point ()
  "Return bounds of quoted string at point using `helixel--bounds-quote-char'.
Temporarily sets the quote character's syntax to string-quote and
ensures backslash has escape syntax."
  (when helixel--bounds-quote-char
    (with-syntax-table (copy-syntax-table (syntax-table))
      (unless (= (char-syntax helixel--bounds-quote-char) ?\")
        (modify-syntax-entry helixel--bounds-quote-char "\""))
      ;; Ensure backslash acts as an escape character so that \"
      ;; inside strings is treated as an escaped quote, not a string
      ;; terminator.  Necessary in modes like text-mode where \ has
      ;; no escape syntax by default.
      (unless (= (char-syntax ?\\) ?\\)
        (modify-syntax-entry ?\\ "\\"))
      (syntax-ppss-flush-cache (point-min))
      (helixel--bounds-of-string-at-point))))

(put 'helixel-quote 'forward-op #'helixel--forward-quote)
(put 'helixel-quote 'bounds-of-thing-at-point
     #'helixel--bounds-of-quote-at-point)

;; ── Simple quote (character-based, for use inside comments/strings) ──

(defun helixel--preceded-by-odd-backslashes-p (pos)
  "Return non-nil if POS is preceded by an odd number of backslashes."
  (let ((n 0))
    (while (and (> pos (point-min))
                (eq (char-before pos) ?\\))
      (setq n (1+ n)
            pos (1- pos)))
    (= (logand n 1) 1)))

(defun helixel--bounds-of-quote-simple-at-point ()
  "Return bounds (BEG . END) of a simple quoted string at point.
Uses `helixel--bounds-quote-char' as delimiter and searches
literally without syntax tables.  Handles backslash-escaped quotes.
Returns nil if point is not inside a simple quoted string."
  (when helixel--bounds-quote-char
    (let* ((q helixel--bounds-quote-char)
           (qstr (char-to-string q))
           (orig (point)))
      (save-excursion
        ;; Start backward search from one past point so that
        ;; a quote at the current position is included.
        (unless (eobp) (forward-char))
        (catch 'helixel--found
          (while (search-backward qstr nil t)
            (unless (helixel--preceded-by-odd-backslashes-p (point))
              (let ((candidate-open (point)))
                ;; Use save-excursion so failed forward searches
                ;; don't move point away from the backward scan.
                (save-excursion
                  (goto-char (1+ candidate-open))
                  (let (close)
                    (while (and (not close)
                                (search-forward qstr nil t))
                      (let ((qpos (1- (point))))
                        (unless (helixel--preceded-by-odd-backslashes-p
                                 qpos)
                          (setq close (point)))))
                    (when (and close
                               (>= orig candidate-open)
                               (<= orig close))
                      (throw 'helixel--found
                             (cons candidate-open close))))))))
          nil)))))

(defun helixel--forward-quote-simple (&optional count)
  "Move forward COUNT simple quoted strings.
Uses `helixel-forward-quote-char' as delimiter and searches literally
without syntax tables.  Returns 0 on success, or (* dir remaining) on
failure."
  (setq count (or count 1))
  (let* ((q helixel-forward-quote-char)
         (qstr (char-to-string q))
         (dir (if (> count 0) 1 -1))
         (n (abs count)))
    (while (and (> n 0)
                (if (> dir 0)
                    ;; ── Forward ──
                    ;; Find next unescaped opening quote.
                    (let ((open nil))
                      (while (and (not open) (not (eobp)))
                        (if (search-forward qstr nil t)
                            (let ((qpos (1- (point))))
                              (unless (helixel--preceded-by-odd-backslashes-p
                                       qpos)
                                (setq open qpos)))
                          (setq n 0)))
                      (when open
                        ;; Find matching unescaped closing quote.
                        (goto-char (1+ open))
                        (let ((close nil))
                          (while (and (not close) (not (eobp)))
                            (if (search-forward qstr nil t)
                                (let ((qpos (1- (point))))
                                  (unless
                                      (helixel--preceded-by-odd-backslashes-p
                                       qpos)
                                    (setq close (point))))
                              (setq n 0)))
                          (if close
                              (progn (goto-char close) (setq n (1- n)) t)
                            (setq n 0) nil))))
                  ;; ── Backward ──
                  ;; Find previous unescaped quote (treat as closer).
                  (let ((close nil))
                    (while (and (not close) (not (bobp)))
                      (if (search-backward qstr nil t)
                          (unless (helixel--preceded-by-odd-backslashes-p
                                   (point))
                            (setq close (point)))
                        (setq n 0)))
                    (when close
                      ;; Find matching opener before this closer.
                      (let ((open nil))
                        (while (and (not open) (not (bobp)))
                          (if (search-backward qstr nil t)
                              (unless (helixel--preceded-by-odd-backslashes-p
                                       (point))
                                (setq open (point)))
                            (setq n 0)))
                        (if open
                            (progn (goto-char open) (setq n (1- n)) t)
                          (setq n 0) nil)))))))
    (* dir n)))

(put 'helixel-quote-simple 'forward-op #'helixel--forward-quote-simple)
(put 'helixel-quote-simple 'bounds-of-thing-at-point
     #'helixel--bounds-of-quote-simple-at-point)

(defun helixel-select-quote-thing
    (thing beg end _type count &optional inclusive)
  "Selection THING as if it described a quoted object.
THING is typically either `helixel-quote' or `helixel-chars'.  This
function is called from `helixel-select-quote'.
BEG and END specify the current selection bounds.
COUNT is the number of objects to select.
INCLUSIVE indicates whether to include the delimiters."
  (save-excursion
    (let* ((count (or count 1))
           (dir (if (> count 0) 1 -1))
           (bnd (let ((b (bounds-of-thing-at-point thing)))
                  (and b (< (point) (cdr b)) b)))
           addcurrent
           wsboth)
      (if inclusive (setq inclusive t)
        (when (= (abs count) 2)
          (setq count dir)
          (setq inclusive 'quote-only))
        ;; never extend with exclusive selection
        (setq beg nil end nil))
      ;; check if the previously selected range does not contain a
      ;; string
      (unless (and beg end
                   (save-excursion
                     (goto-char (if (> dir 0) beg end))
                     (forward-thing thing dir)
                     (and (<= beg (point)) (< (point) end))))
        ;; if so forget the range
        (setq beg nil end nil))
      ;; check if there is a current object, if not fetch one
      (when (not bnd)
        (unless (and (zerop (forward-thing thing dir))
                     (setq bnd (bounds-of-thing-at-point thing)))
          (user-error "No quoted string found"))
        (if (> dir 0)
            (setq end (point))
          (setq beg (point)))
        (setq addcurrent t))
      ;; check if current object is not selected
      (when (or (not beg) (not end) (> beg (car bnd)) (< end (cdr bnd)))
        ;; if not, enlarge selection
        (when (or (not beg) (< (car bnd) beg)) (setq beg (car bnd)))
        (when (or (not end) (> (cdr bnd) end)) (setq end (cdr bnd)))
        (setq addcurrent t wsboth t))
      ;; maybe count current element
      (when addcurrent
        (setq count (if (> dir 0) (1- count) (1+ count))))
      ;; enlarge selection
      (goto-char (if (> dir 0) end beg))
      (when (and (not addcurrent)
                 (= count (forward-thing thing count)))
        (user-error "No quoted string found"))
      (if (> dir 0) (setq end (point)) (setq beg (point)))
      ;; add whitespace
      (cond
       ((not inclusive) (setq beg (1+ beg) end (1- end)))
       ((not (eq inclusive 'quote-only))
        ;; try to add whitespace in forward direction
        (goto-char (if (> dir 0) end beg))
        (if (setq bnd (bounds-of-thing-at-point 'helixel-space))
            (if (> dir 0) (setq end (cdr bnd)) (setq beg (car bnd)))
          ;; if not found try backward direction
          (goto-char (if (> dir 0) beg end))
          (if (and wsboth (setq bnd (bounds-of-thing-at-point 'helixel-space)))
              (if (> dir 0) (setq beg (car bnd)) (setq end (cdr bnd)))))))
      (helixel-range beg end nil :expanded t))))

(defun helixel-select-quote (quote beg end type count &optional inclusive)
  "Return a range (BEG END) of COUNT quoted text objects.
QUOTE specifies the quotation delimiter.  BEG END TYPE are the
currently selected (visual) range.

If INCLUSIVE is nil the previous selection is ignore.  If there is
quoted string at point this object will be selected, otherwise
the following (if (> COUNT 0)) or preceeding object (if (< COUNT
0)) is selected.  If (/= (abs COUNT) 2) the delimiting quotes are not
contained in the range, otherwise they are contained in the range.

If INCLUSIVE is non-nil the selection depends on the previous
selection.  If the currently selection contains at least one
character that is contained in a quoted string then the selection
is extended, otherwise it is thrown away.  If there is a
non-selected object at point then this object is added to the
selection.  Otherwise the selection is extended to the
following (if (> COUNT 0)) or preceeding object (if (< COUNT
0)).  Any whitespace following (or preceeding if (< COUNT 0)) the
new selection is added to the selection.  If no such whitespace
exists and the selection contains only one quoted string then the
preceeding (or following) whitespace is added to the range."
  (let ((helixel-forward-quote-char quote)
        (helixel--bounds-quote-char quote))
    (or (let* ((comment-bnd (bounds-of-thing-at-point 'helixel-comment))
               (bnd (or comment-bnd
                        (bounds-of-thing-at-point 'helixel-string))))
          (when (and bnd (< (point) (cdr bnd))
                     (/= (char-after (car bnd)) quote)
                     ;; Only check the closing delimiter when we are
                     ;; inside a string (not a comment).  Comments are
                     ;; delimited by //, \n or /*, */ — never by a
                     ;; quote character, so the closing-delimiter check
                     ;; is both unnecessary and harmful (e.g. when the
                     ;; last character before the comment end is a
                     ;; quote).
                     (or comment-bnd
                         (/= (char-before (cdr bnd)) quote)))
            (helixel-with-restriction (car bnd) (cdr bnd)
              (ignore-errors (helixel-select-quote-thing
                              'helixel-quote-simple
                              beg end type
                              count
                              inclusive)))))
        (helixel-select-quote-thing 'helixel-quote
                                    beg end type
                                    count
                                    inclusive))))

;; ── XML / SGML tag selection ──

(defun helixel-select-xml-tag (beg end type &optional count inclusive)
  "Return a range (BEG END) of COUNT matching XML tags.
TYPE is the selection type.  If INCLUSIVE is non-nil, the tags
themselves are included from the range."
  (unless inclusive (setq inclusive 'exclusive-line))
  (cond
   ((and (eq inclusive 'exclusive-line) (= (abs (or count 1)) 1))
    (let ((rng (helixel-select-block #'helixel-up-xml-tag beg end type
                                     count 'exclusive-line t)))
      (if (or (and beg (= beg (helixel-range-beginning rng))
                   end (= end (helixel-range-end rng))))
          (helixel-select-block #'helixel-up-xml-tag beg end type count t)
        rng)))
   (t
    (helixel-select-block #'helixel-up-xml-tag beg end type count inclusive))))

(defun helixel--xml-tag-name (bounds)
  "Extract XML tag name from tag BOUNDS (BEG . END).
Returns the tag name without <, </, or >."
  (let ((str (buffer-substring (car bounds) (cdr bounds))))
    (if (string-match "\\`<\\(/\\)?\\([^ >\n]+\\)" str)
        (match-string 2 str)
      "")))

(defun helixel--tag-regex (tag-name)
  "Return a regex matching <TAG-NAME...> or </TAG-NAME>.
Group 1 captures the slash for closing tags."
  (concat "<\\(/\\)?" (regexp-quote tag-name)
          "\\(?:>\\|[ \n]\\(?:[^\"/>]\\|\"[^\"]*\"\\)*?>\\)"))

(defun helixel--find-matching-tag-close (tag-name)
  "Search forward from point for matching </TAG-NAME>, counting nested pairs.
Point should be right after the opening <TAG-NAME>.
Sets `match-data' for the closing tag on success, returns 0."
  (let ((regex (helixel--tag-regex tag-name))
        (depth 1))
    (while (and (> depth 0) (re-search-forward regex nil t))
      (setq depth (+ depth (if (match-string 1) -1 +1))))
    (if (zerop depth)
        0
      (user-error "No matching closing tag for %s" tag-name))))

(defun helixel--tag-move-past-markup (&optional dir)
  "Move point past XML tag markup if inside one.
This lets the tag finder locate the enclosing pair.

For backward search (DIR < 0):
  - On or inside opening tag like <div|> → move after >
  - On or inside closing tag like </div|> → move before <

For forward search (DIR > 0):
  - On or inside opening tag like <div|> → move before <
  - On or inside closing tag like </div|> → move after >

Returns non-nil if point was adjusted."
  (let* (;; If point is on <, that's the tag we're inside.
         (on-lt (and (eq (char-after) ?<) (point)))
         ;; Otherwise search backward for the nearest < before point.
         (lt-pos (or on-lt
                     (save-excursion
                       (search-backward "<"
                                        (line-beginning-position) t)))))
    (when lt-pos
      (let ((gt-pos (save-excursion
                      (goto-char lt-pos)
                      (search-forward ">" (line-end-position) t))))
        (when (and gt-pos (> gt-pos (point)))
          ;; Point is strictly between < and > (not at >)
          (if (eq (char-after (1+ lt-pos)) ?/)
              ;; Closing tag
              (if (< (or dir 0) 0)
                  (goto-char lt-pos)    ; backward: move before <
                (goto-char gt-pos))     ; forward: move after >
            ;; Opening tag
            (if (< (or dir 0) 0)
                (goto-char gt-pos)      ; backward: move after >
              (goto-char lt-pos)))      ; forward: move before <
          t)))))

(defun helixel--tag-find-opener-backward ()
  "Search backward for the nearest *unclosed* XML opening tag.
Balances closing tags as we go backward so the returned opener
is the innermost tag that still encloses point.  When a matched
opener is found (depth drops to 0), it is returned as the
enclosing tag.  Returns 0 on success with `match-data' set, 1 on
failure."
  (let ((depth 0)
        (saved-match nil)
        (regex (concat "<\\([^/ >\n]+\\)"
                       "\\(?:=>?\\|[^\"/>]\\|\"[^\"]*\"\\)*?>\\|"
                       "</\\([^>]+?\\)>")))
    (catch 'helixel--found
      (while (re-search-backward regex nil t)
        (if (match-beginning 1)
            ;; Opening tag
            (if (> depth 0)
                (progn
                  (setq depth (1- depth))
                  ;; When depth reaches 0, this opener balances the
                  ;; pending closer — it is our enclosing tag.
                  (when (zerop depth)
                    (setq saved-match (match-data t))))
              ;; depth=0: unclosed opener found — this is the
              ;; innermost enclosing tag.
              (throw 'helixel--found 0))
          ;; Closing tag
          (setq depth (1+ depth))))
      ;; If we exhausted the buffer, use the last balanced opener.
      (if saved-match
          (progn
            (set-match-data saved-match)
            0)
        1))))

(defun helixel--tag-adjust-for-jump ()
  "Move point inside the tag pair whose boundary point is on.
If point is on or inside an opening tag (<div|>), move after >.
If point is on or after a closing tag (</div|>), move before <.
This is used by `helixel-jump-to-match' so that the enclosing-pair
lookup finds the pair whose delimiter point is on, rather than the
outer enclosing pair."
  (let ((c (char-after)))
    (cond
     ;; On < of an opening tag → move after >
     ((and c (eq c ?<)
           (not (eq (char-after (1+ (point))) ?/)))
      (search-forward ">" (line-end-position) t))
     ;; On < of a closing tag → move before <
     ((and c (eq c ?<)
           (eq (char-after (1+ (point))) ?/))
      (backward-char))
     ;; Right after > of a closing tag → move before < of that tag
     ((and (not (bobp)) (eq (char-before) ?>))
      (backward-char)
      (let ((lt (search-backward "<" (line-beginning-position) t)))
        (when (and lt (eq (char-after (1+ lt)) ?/))
          (goto-char lt))))
     ;; Inside a closing tag (after </ and before >) → move before <
     ((and (not (bobp))
           (save-excursion
             (search-backward "<" (line-beginning-position) t)
             (eq (char-after (1+ (point))) ?/)))
      ;; Point is inside </xxx> markup
      (search-backward "<" (line-beginning-position) t)
      (goto-char (match-beginning 0))))))

(defun helixel-up-xml-tag (&optional count)
  "Move point to the end or beginning of balanced xml tags.
If COUNT is greater than zero point is moved forward otherwise it is moved
backwards.  Whenever an opening delimiter is found the COUNT is increased by
one, if a closing delimiter is found the COUNT is decreased by one.  The motion
stops when COUNT reaches zero.  The match data reflects the last successful
match (that caused COUNT to reach zero)."
  (let* ((dir (if (> (or count 1) 0) +1 -1))
         (count (abs (or count 1)))
         (op (if (> dir 0) 1 2))
         (cl (if (> dir 0) 2 1))
         pnt tags match)
    (catch 'done
      (while (> count 0)
        ;; find the previous opening tag
        (while
            (and (setq match
                       (re-search-forward
                        (concat "<\\([^/ >\n]+\\)"
                                "\\(?:=>?\\|[^\"/>]\\|"
                                "\"[^\"]*\"\\)*?>\\|"
                                "</\\([^>]+?\\)>")
                        nil t dir))
                 (cond
                  ((match-beginning op)
                   (push (match-string op) tags))
                  ((null tags) nil) ; free closing tag
                  ((and (< dir 0)
                        (string= (car tags) (match-string cl)))
                   ;; in backward direction we only accept matching
                   ;; tags.  If the current tag is a free opener
                   ;; without matching closing tag, the subsequent
                   ;; test will make us ignore this tag
                   (pop tags)
                   tags)
                  ((and (< dir 0) tags)
                   ;; backward: non-matching opener nested inside — skip
                   tags)
                  ((and (> dir 0))
                   ;; non matching openers are considered free openers
                   (while (and tags
                               (not (string= (car tags)
                                             (match-string cl))))
                     (pop tags))
                   (pop tags)
                   tags))))
        (unless (setq match (and match (match-data t)))
          (setq match nil)
          (throw 'done count))
        ;; found closing tag, look for corresponding opening tag
        (cond
         ((> dir 0)
          (setq pnt (match-end 0))
          (goto-char (match-beginning 0)))
         (t
          (setq pnt (match-beginning 0))
          (goto-char (match-end 0))))
        (let* ((tag (match-string cl))
               (refwd (helixel--tag-regex tag))
               (cnt 1))
          (while (and (> cnt 0) (re-search-backward refwd nil t dir))
            (setq cnt (+ cnt (if (match-beginning 1) dir (- dir)))))
          (if (zerop cnt) (setq count (1- count) tags nil))
          (goto-char pnt)))
      (if (> count 0)
          (set-match-data nil)
        (set-match-data match)
        (goto-char (if (> dir 0) (match-end 0) (match-beginning 0)))))
    ;; if not found, set to point-max/point-min
    (unless (zerop count)
      (set-match-data nil)
      (goto-char (if (> dir 0) (point-max) (point-min))))
    (* dir count)))
(put 'helixel-up-xml-tag 'helixel--match-close
     #'helixel--find-matching-tag-close)

;; ── Delimiter constructors ──

(defun helixel--find-quote-pair (quote-char dir)
  "Find matching quote pair for QUOTE-CHAR in direction DIR.
DIR = -1: find opening unescaped quote before point, set `match-data', return 0.
DIR = +1: find matching closing unescaped quote, set `match-data', return 0.
Returns non-zero on failure.
Handles backslash-escaped quotes via `helixel--preceded-by-odd-backslashes-p'."
  (let ((qstr (char-to-string quote-char)))
    (if (> dir 0)
        ;; Forward balanced search: count depth, stop at 0.
        (let ((depth 1))
          (while (and (> depth 0) (re-search-forward qstr nil t))
            (unless (helixel--preceded-by-odd-backslashes-p (1- (point)))
              (setq depth (1- depth))))
          (if (zerop depth) 0 1))
      ;; Backward: find the first unescaped quote before point.
      (if (and (re-search-backward qstr nil t)
               (not (helixel--preceded-by-odd-backslashes-p (point))))
          0
        1))))

(defun helixel-make-pair-delimiter (open close)
  "Create a pair delimiter for OPEN and CLOSE characters.
Returns a `helixel-delimiter' struct with type :pair (pure data)."
  (helixel--make-delimiter-raw
   :type :pair
   :open open :close close))

(defun helixel-make-tag-delimiter ()
  "Create a tag delimiter.
Returns a `helixel-delimiter' struct with type :tag."
  (helixel--make-delimiter-raw
   :type :tag
   :open "<"
   :match-close #'helixel--find-matching-tag-close))


(provide 'helixel-textobj-pair)
;;; helixel-textobj-pair.el ends here
