;;; helixel-move.el --- Move & sel commands  -*- lexical-binding: t; -*-

;; Copyright (C) 2025-2026  jixiuf

;; Author: jixiuf <https://github.com/jixiuf>
;; Keywords: convenience
;; URL: https://github.com/jixiuf/helixel-mode
;; SPDX-License-Identifier: GPL-3.0-or-later

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:

;; Movement and selection commands for helixel-mode.
;;
;; Provides `helixel-define-movement' for wrapping built-in commands with
;; action tracking, plus hand-written word/WORD/symbol movement commands,
;; line/rectangle selection, surround-thing-at-point, and the line-wise
;; and rect-wise kill/yank helpers.
;;
;; Also houses `helixel--rect-change' and `helixel--rect-replay' for
;; rectangle-change-with-replay support, and `helixel--replace-region'
;; / `helixel-replace-char' for character replacement.

;;; Code:

(require 'cl-lib)
(require 'rect)
(require 'helixel-state)

(require 'helixel-macros)

(defvar helixel-block-textobj-alist)

;; Forward-declare from helixel-textobj.el (mutual deps via helixel-state).
(declare-function helixel--block-spec-at-point "helixel-textobj" ())

;; All-buffer/all-dir line handlers (defined in helixel-repeat.el).
(declare-function helixel--all-buffer-line "helixel-repeat"
                  (edit prefix))
(declare-function helixel--all-dir-line "helixel-repeat"
                  (edit))

(defmacro helixel-define-movement (name builtin type &rest options)
  "Define a movement command NAME wrapping BUILTIN with TYPE.

OPTIONS is a plist supporting:
  :clear-highlights BOOL - clear highlights before executing (default t)
  :reverse CMD        - opposite-direction command for \=`-,' flip

  (helixel-define-movement helixel-forward-char forward-char char)

Without highlights clearing:
  (helixel-define-movement helixel-scroll-up scroll-up-command scroll
                        :clear-highlights nil)

Movement commands are replayed at fake cursors via
\=`call-interactively` (the mc dispatcher falls back to it when
the action carries no tx with a runner)."
  (declare (indent 1)
           (debug (&define name sexp sexp [&rest keywordp sexp] def-body)))
  (let ((clear (if (plist-member options :clear-highlights)
                   (plist-get options :clear-highlights)
                 t))
        (rev (plist-get options :reverse)))
    `(progn
       (helixel-define-command ,name
           (:category movement :subcat ,type
                      :clear-highlights ,clear
                      ,@(when rev
                          `(:motion-extra
                            (list :reverse-command ',rev))))
         ;; Clear stale pending-sel so pure motion commands
         ;; (j, gh, etc.) don't inherit a selection from a prior
         ;; edit (e.g. insert-selection-end from insert-exit).
         ;; Preserve when pending-sel is a structured kind
         ;; (line/rect/textobj) so operators (d/y/c) can read the
         ;; selection type even after a movement (e.g. x j d).
         (unless (memq (and helixel--pending-sel
                            (helixel-sel-kind helixel--pending-sel))
                       '(line rect textobj))
           (setq helixel--pending-sel nil))
         (call-interactively #',builtin))
       ,@(when rev `((helixel-register-motion-reverse ',name ',rev))))))

(defmacro helixel-define-movements (&rest specs)
  "Register multiple movements from SPECS.
Each element of SPECS is a list of args for `helixel-define-movement'.

Example:
  (helixel-define-movements
    (helixel-forward-char forward-char char)
    (helixel-next-line next-line line))"
  `(progn
     ,@(mapcar (lambda (s) `(helixel-define-movement ,@s)) specs)))

;; ── Simple movement wrappers ──
;; Generated by helixel-define-movement for builtin commands that only need
;; action tracking + highlight clearing + call-interactively.

(helixel-define-movement helixel-backward-char backward-char char
                         :reverse helixel-forward-char)
(helixel-define-movement helixel-forward-char forward-char char
                         :reverse helixel-backward-char)
(helixel-define-movement helixel-next-line next-line line
                         :reverse helixel-previous-line)
(helixel-define-movement helixel-previous-line previous-line line
                         :reverse helixel-next-line)
(helixel-define-movement helixel-go-beginning-line beginning-of-line goto)
(helixel-define-movement helixel-go-end-line end-of-line goto)
(helixel-define-movement helixel-go-first-nonwhitespace
  back-to-indentation goto)
(helixel-define-movement helixel-go-end-buffer end-of-buffer goto)

(helixel-define-movement helixel-scroll-up-command scroll-up-command scroll
                         :clear-highlights nil)
(helixel-define-movement helixel-scroll-down-command scroll-down-command scroll
                         :clear-highlights nil)

;; ── Word / WORD / Symbol movement ──

(defmacro helixel--with-movement-surround (&rest body)
  "Create a region around movement defined in BODY.
If a region is already active, no new region is created.

Movement commands redefine the selection, so they reset
`helixel--sel-type' to nil - a previous `line' / `rect'
label from `x' / `v' must not bleed into the new region (which
would make `y' tag the kill as line-wise even when the user
selected a word).

For the same reason, any non-movement pending-sel is cleared:
a general movement replaces the selection intent, so the stale
line/rect/textobj sel must not leak into `helixel-record-action'
and subsequently into dot-repeat.

INVARIANT: after this macro, `helixel--pending-sel' is either nil
or already a movement-kind sel - it never holds a line/rect/textobj
sel that was pushed by a prior special-selection command.

Note: `helixel-define-command' handles `clear-highlights'
and `track-visual-move'
automatically, so this macro only does `push-mark' + activate."
  (declare (indent 0) (debug def-body))
  `(let ((current (point)))
     ;; Clear stale non-movement pending-sel BEFORE the body so
     ;; `helixel--track-visual-move' (injected by the macro) sees
     ;; a nil ctx and creates a fresh movement sel.  This keeps
     ;; pending-sel in sync with sel-type (both nil).
     ;; Note: do NOT gate on `use-region-p' - highlight clearing
     ;; may have deactivated the mark before we run.
     (helixel--clear-non-movement-pending-sel)

     ,@body
     (unless (use-region-p)
       (push-mark current t 'activate))))

;; ── Word / WORD / symbol movement commands ──
;;
;; All twelve forward/backward × word/WORD/symbol × start/end commands
;; share the same body shape; we generate them via
;; `helixel--def-thing-move'.  Some `:side' values are NOT mechanical
;; (helixel-backward-WORD uses :a, helixel-backward-symbol-start uses
;; :a, helixel-backward-symbol-end uses :inner - preserved verbatim
;; from the original definitions).

(defmacro helixel--def-thing-move (name subcat thing fwd-fn sign side
                                        &optional reverse-cmd)
  "Define a thing-movement command.
NAME is the command symbol; SUBCAT the :subcat tag; THING the
thing category (`helixel-word' / -WORD / -symbol);
FWD-FN is one of `forward-beginning' / `forward-end' (interned
relative to `helixel--');  SIGN is +1 or -1; SIDE is :a or :inner.
Optional REVERSE-CMD is the opposite-direction command for
\=`-,' permanent flip support."
  (declare (indent 0)
           (debug (&define name sexp sexp sexp sexp sexp &optional sexp)))
  (let* ((fn (intern (format "helixel--%s" fwd-fn)))
         ;; Only skip newlines for single-line things (word/WORD/symbol).
         ;; Multi-line things like paragraph/sentence/function naturally
         ;; span lines and should not have newlines skipped.
         (single-line-p (memq thing helixel--single-line-things)))
    `(progn
       (helixel-define-command ,name
           (:category movement :subcat ,subcat
                      :params (&optional count)
                      ,@(when reverse-cmd
                          `(:motion-extra
                            (list :reverse-command ',reverse-cmd))))
         (interactive "p")
         ;; Skip past a newline before capturing the motion origin,
         ;; so \n is not treated as a separate word.
         ,@(when single-line-p `((helixel--skip-newline ,sign)))
         (if (memq ',thing helixel-thing-move-no-select-things)
             (progn
               ;; Clean up stale state (same as with-movement-surround)
               ;; but skip the visual selection (push-mark + activate).
               (helixel--clear-non-movement-pending-sel)

               (,fn ',thing (* ,sign (or count 1))))
           (helixel--with-movement-surround
             (,fn ',thing (* ,sign (or count 1)))))
         (helixel--set-mark-region ',thing ,side))
       ,@(when reverse-cmd
           `((helixel-register-motion-reverse ',name ',reverse-cmd))))))

(helixel--def-thing-move helixel-forward-word-start
                         word helixel-word forward-beginning  1 :a
                         helixel-backward-word-start)
(helixel--def-thing-move helixel-forward-word-end
                         word helixel-word forward-end        1 :inner
                         helixel-backward-word-end)
(helixel--def-thing-move helixel-backward-word-start
                         word helixel-word forward-beginning -1 :inner
                         helixel-forward-word-start)
(helixel--def-thing-move helixel-backward-word-end
                         word helixel-word forward-end       -1 :a
                         helixel-forward-word-end)

(helixel--def-thing-move helixel-forward-WORD-start
                         WORD helixel-WORD forward-beginning  1 :a
                         helixel-backward-WORD)
(helixel--def-thing-move helixel-forward-WORD-end
                         WORD helixel-WORD forward-end        1 :inner
                         helixel-backward-WORD-end)
(helixel--def-thing-move helixel-backward-WORD
                         WORD helixel-WORD forward-beginning -1 :a
                         helixel-forward-WORD-start)
(helixel--def-thing-move helixel-backward-WORD-end
                         WORD helixel-WORD forward-end       -1 :inner
                         helixel-forward-WORD-end)

(helixel--def-thing-move helixel-forward-symbol-start
                         symbol helixel-symbol forward-beginning  1 :a
                         helixel-backward-symbol-start)
(helixel--def-thing-move helixel-forward-symbol-end
                         symbol helixel-symbol forward-end        1 :inner
                         helixel-backward-symbol-end)
(helixel--def-thing-move helixel-backward-symbol-start
                         symbol helixel-symbol forward-beginning -1 :a
                         helixel-forward-symbol-start)
(helixel--def-thing-move helixel-backward-symbol-end
                         symbol helixel-symbol forward-end       -1 :inner
                         helixel-forward-symbol-end)

(defmacro helixel--define-delimiter-movement (name outer-p forward-p
                                                   reverse delim-expr)
  "Define a delimiter movement command NAME.
OUTER-P non-nil → outer (a), nil → inner (i).
FORWARD-P non-nil → forward-to-end (] }), nil → outward-to-open ([ {).
REVERSE is the opposite-direction command symbol.
DELIM-EXPR is an expression that evaluates to a `helixel-delimiter' struct."
  (declare (indent defun) (debug (&define name sexp sexp sexp form)))
  (let ((inner-p (not outer-p)))
    `(progn
       (helixel-define-command ,name
           (:category movement :subcat pair :clear-highlights nil
                      :params (&optional count)
                      :motion-extra (list :delim (lambda () ,delim-expr)
                                          :delim-inner-p ,inner-p
                                          :delim-forward-p ,forward-p
                                          :reverse-command ',reverse))
         (interactive "p")
         (let* ((n (abs (or count 1)))
                (flipped (< (or count 1) 0))
                (eff-forward-p (if flipped (not ,forward-p) ,forward-p))
                (eff-inner-p ,inner-p)
                (eff-bounds-fn (if eff-forward-p
                                   'helixel--generic-bounds-next
                                 'helixel--generic-bounds-previous))
                (eff-motion-extra (list :delim (lambda () ,delim-expr)
                                        :delim-inner-p eff-inner-p
                                        :delim-forward-p eff-forward-p)))
           (helixel--clear-non-movement-pending-sel)
           (deactivate-mark)
           ;; Override the motion-extra recorded by
           ;; helixel-define-command with our flipped version
           ;; so \\[helixel-repeat-last-motion] and \\[helixel-action-cycle]
           ;; see the actual direction used.
           (setq helixel--motion-extra eff-motion-extra)
           (dotimes (_ n)
             (let* ((d ,delim-expr)
                    (b (funcall eff-bounds-fn d eff-inner-p)))
               (when b
                 (helixel--set-mark-region b)
                 (let ((pos (if eff-forward-p (cdr b) (car b))))
                   (goto-char pos)))))))
       (helixel-register-motion-reverse ',name ',reverse))))

;; ── Pair delimiters (parens, brackets, braces, angle, quotes) ──

(defmacro helixel--define-pair-delimiter-family (stem open close)
  "Define the 4 outer/inner movement commands for a delimiter pair.
STEM is the name fragment (e.g. paren, bracket, brace).
OPEN and CLOSE are the delimiter characters.
Generates commands: helixel-outer-STEM, helixel-next-STEM-end,
helixel-inner-outer-STEM, helixel-inner-next-STEM-end."
  (declare (indent 1))
  (let ((outer-cmd (intern (format "helixel-outer-%s" stem)))
        (next-end-cmd (intern (format "helixel-next-%s-end" stem)))
        (inner-outer-cmd (intern (format "helixel-inner-outer-%s" stem)))
        (inner-next-end-cmd
         (intern (format "helixel-inner-next-%s-end" stem)))
        (delim-form `(helixel-make-pair-delimiter ,open ,close)))
    `(progn
       (helixel--define-delimiter-movement ,outer-cmd t nil
         ,next-end-cmd ,delim-form)
       (helixel--define-delimiter-movement ,next-end-cmd t t
         ,outer-cmd ,delim-form)
       (helixel--define-delimiter-movement ,inner-outer-cmd nil nil
         ,inner-next-end-cmd ,delim-form)
       (helixel--define-delimiter-movement ,inner-next-end-cmd nil t
         ,inner-outer-cmd ,delim-form))))

(helixel--define-pair-delimiter-family paren ?\( ?\))
(helixel--define-pair-delimiter-family bracket ?\[ ?\])
(helixel--define-pair-delimiter-family brace ?{ ?})
(helixel--define-pair-delimiter-family angle ?< ?>)
(helixel--define-pair-delimiter-family double-quote ?\" ?\")
(helixel--define-pair-delimiter-family single-quote ?' ?')
(helixel--define-pair-delimiter-family back-quote ?` ?`)

;; ── Tag / Block delimiter movement ──

(defmacro helixel--define-singleton-delimiter-family (stem factory-form)
  "Define 4 movement commands for a zero-arg delimiter like tag/block.
STEM is the name fragment.  FACTORY-FORM produces the delimiter."
  (declare (indent 1))
  (let ((outer-cmd (intern (format "helixel-outer-%s" stem)))
        (next-end-cmd (intern (format "helixel-next-%s-end" stem)))
        (inner-outer-cmd (intern (format "helixel-inner-outer-%s" stem)))
        (inner-next-end-cmd
         (intern (format "helixel-inner-next-%s-end" stem))))
    `(progn
       (helixel--define-delimiter-movement ,outer-cmd t nil
         ,next-end-cmd ,factory-form)
       (helixel--define-delimiter-movement ,next-end-cmd t t
         ,outer-cmd ,factory-form)
       (helixel--define-delimiter-movement ,inner-outer-cmd nil nil
         ,inner-next-end-cmd ,factory-form)
       (helixel--define-delimiter-movement ,inner-next-end-cmd nil t
         ,inner-outer-cmd ,factory-form))))

(helixel--define-singleton-delimiter-family
    tag (helixel-make-tag-delimiter))
(helixel--define-singleton-delimiter-family
    block (helixel-make-block-delimiter))

;; `helixel--generic-bounds-at' / `helixel--generic-bounds-next'
;; are defined in helixel-core.el.

;; ── Paragraph / sentence / function movement commands ──
;; All twelve commands here use :side :a (verbatim from originals).

(helixel--def-thing-move helixel-forward-paragraph-start
                         paragraph helixel-paragraph forward-beginning  1 :a
                         helixel-backward-paragraph-start)
(helixel--def-thing-move helixel-backward-paragraph-start
                         paragraph helixel-paragraph forward-beginning -1 :a
                         helixel-forward-paragraph-start)
(helixel--def-thing-move helixel-forward-paragraph-end
                         paragraph helixel-paragraph forward-end        1 :a
                         helixel-backward-paragraph-end)
(helixel--def-thing-move helixel-backward-paragraph-end
                         paragraph helixel-paragraph forward-end       -1 :a
                         helixel-forward-paragraph-end)

(helixel--def-thing-move helixel-forward-sentence-end
                         sentence helixel-sentence forward-end          1 :a
                         helixel-backward-sentence-end)
(helixel--def-thing-move helixel-backward-sentence-start
                         sentence helixel-sentence forward-beginning   -1 :a
                         helixel-forward-sentence-start)
(helixel--def-thing-move helixel-forward-sentence-start
                         sentence helixel-sentence forward-beginning    1 :a
                         helixel-backward-sentence-start)
(helixel--def-thing-move helixel-backward-sentence-end
                         sentence helixel-sentence forward-end         -1 :a
                         helixel-forward-sentence-end)

(helixel--def-thing-move helixel-forward-function-end
                         function helixel-function forward-end          1 :a
                         helixel-backward-function-end)
(helixel--def-thing-move helixel-backward-function-start
                         function helixel-function forward-beginning   -1 :a
                         helixel-forward-function-start)
(helixel--def-thing-move helixel-forward-function-start
                         function helixel-function forward-beginning    1 :a
                         helixel-backward-function-start)
(helixel--def-thing-move helixel-backward-function-end
                         function helixel-function forward-end         -1 :a
                         helixel-forward-function-end)

(defun helixel--jump-target-for-delimiter (d orig &optional no-close-backoff
                                             mark-thing)
  "Try to find a jump target using delimiter D.
ORIG is the original point.  Returns (TARGET . (OB . CE)) on success,
or nil if no enclosing pair found.
When NO-CLOSE-BACKOFF is non-nil, passed through to `helixel-delimiter-bounds'.
When MARK-THING is non-nil, stores bounds as markers in the
live event's \=:mark-region for `\;' marking."
  (save-excursion
    (when-let* ((adj (helixel-delimiter-adjust-for-jump d)))
      (funcall adj))
    (helixel--with-debug-log jump-to-match-core
      (pcase-let* ((`(,ob ,_oe ,_cb ,ce)
                    (helixel-delimiter-bounds-flat d no-close-backoff)))
        (when mark-thing
          (helixel--set-mark-region (cons ob ce)))
        (cons (if (<= (abs (- orig ob)) (abs (- orig ce))) ce ob)
              (cons ob ce)))
      (error nil))))

(defun helixel--jump-syntax-table (char-a char-b orig)
  "Try to jump via syntax-table from any position.
Returns a cons (TARGET . (OB . CE)) on success, or nil.
CHAR-A and CHAR-B are as in `helixel-jump-to-match'.
ORIG is the original point before jumping."
  (save-excursion
    (helixel--with-debug-log jump-syntax-table
      (let ((match-end
             (progn
               (cond
                ((and char-a (memq (char-syntax char-a) '(4 ?\( ?\))))
                 (forward-list 1))
                ((and char-b (memq (char-syntax char-b) '(5 ?\( ?\))))
                 (forward-list -1))
                ;; Only attempt up-list when actually inside a list.
                ;; When depth is 0 (e.g. at BOB before #+begin_src),
                ;; up-list can find spurious close-delimiters from
                ;; syntax-propertize (e.g. \=>\=' in org-mode \=>=\=).
                ((> (nth 0 (syntax-ppss)) 0)
                 (up-list 1))
                (t
                 (signal 'scan-error nil)))
               (point))))
        (goto-char match-end)
        (helixel--with-debug-log jump-syntax-table-backward-list
          (backward-list 1)
          (error nil))
        (let ((b (if (>= match-end (point)) (point) match-end))
              (e (if (>= match-end (point)) match-end (point))))
          (helixel--set-mark-region (cons b e))
          (cons (if (<= (abs (- orig b)) (abs (- orig e))) e b)
                (cons b e))))
      (error nil))))

(defun helixel--pair-chars (&optional type-filter)
  "Return all delimiter chars (open+close) from active surround-pairs.
TYPE-FILTER: :pair, :quote, or nil (all types)."
  (helixel--active-delim-chars :type type-filter))

;; ── Jump-to-match: table builder ──

(defun helixel--jump-match--tables ()
  "Return (OPEN->CLOSE . CLOSE->OPEN) hash tables for pair entries.
Only :pair entries from `helixel--surround-pairs-active' are
included.  Each canonical (open ≤ close) entry maps open→close;
the reverse map is built by swapping keys and values."
  (let* ((open->close (make-hash-table))
         (close->open (make-hash-table)))
    (dolist (e (helixel--surround-pairs-active))
      (when (eq (helixel--surround-entry-type e) :pair)
        (let ((a (helixel--surround-entry-open e))
              (b (helixel--surround-entry-close e)))
          (when (helixel--canonical-pair-p a b)
            (puthash a b open->close)
            (puthash b a close->open)))))
    (cons open->close close->open)))

(defun helixel--jump-match--open-char (char-a char-b open->close close->open)
  "Determine the opening delimiter character at point.
CHAR-A is `char-after', CHAR-B is `char-before'.
OPEN->CLOSE and CLOSE->OPEN are hash tables from
`helixel--jump-match--tables'.
Returns the opening character, or nil if none detected.
Sandwich detection: when between two closers (e.g. \=`))\='),
prefers the inner one (CHAR-B)."
  (or (and char-a (gethash char-a open->close) char-a)
      (and char-b (gethash char-b open->close) char-b)
      (and char-b (gethash char-b close->open))
      (and char-a (gethash char-a close->open))))

;; ── Jump-to-match: four strategy sub-functions ──
;; Each returns (TARGET . DELIMITER) on success, nil on failure.
;; TARGET is the buffer position to jump to; DELIMITER is the
;; matched delimiter plist (nil for syntax-table matches).

(defun helixel--jump-via-pair (open-char close-char char-a orig)
  "Try to jump via a specific pair delimiter.
OPEN-CHAR and CLOSE-CHAR are the delimiter characters.
CHAR-A is the original `char-after' at point.
ORIG is the original point before the jump attempt.
Returns (TARGET . DELIMITER) or nil.

Stepping inside the opener is handled by `adjust-for-jump' on
the delimiter struct, so this function does not duplicate it.
This avoids a double step when the opener is immediately followed
by another opener (e.g. `((foo ...)'), which would confuse the
backward delimiter finder."
  (let* ((d (helixel-make-pair-delimiter open-char close-char))
         (on-opener (and char-a (eq char-a open-char)))
         (equalp (eq open-char close-char)))
    (when-let* ((result (helixel--jump-target-for-delimiter
                         d orig (and on-opener equalp) t)))
      (goto-char (car result))
      (cons (point) d))))

(defun helixel--jump-via-syntax (char-a char-b orig)
  "Try to jump via Emacs syntax-table (`forward-list' / `up-list').
CHAR-A and CHAR-B are as in `helixel--jump-to-match-core'.
ORIG is the original point.
Returns (TARGET . nil) or nil."
  (when-let* ((result (helixel--jump-syntax-table char-a char-b orig)))
    (goto-char (car result))
    (cons (point) nil)))

(defun helixel--jump-via-tag (orig)
  "Try to jump via XML/HTML tag delimiter.
ORIG is the original point.
Returns (TARGET . DELIMITER) or nil."
  (let ((d (helixel-make-tag-delimiter)))
    (when-let* ((result (helixel--jump-target-for-delimiter
                         d orig nil 'helixel-mark-a-tag)))
      (goto-char (car result))
      (cons (point) d))))

(defun helixel--jump-via-block (orig)
  "Try to jump via fenced-block delimiter (org/markdown).
ORIG is the original point.
Returns (TARGET . DELIMITER) or nil.

When point is inside the block (not on a delimiter line),
prefer jumping backward to the block opener so the user can
see the block type and parameters.  When on a delimiter line,
the standard match-jump (farther-end) logic applies."
  (let ((d (helixel-make-block-delimiter)))
    (when-let* ((result (helixel--jump-target-for-delimiter
                         d orig nil t)))
      (let ((target (car result))
            (ob (cadr result))
            (ce (cddr result)))
        ;; When strictly inside the block (not on a delimiter line),
        ;; jump backward to the opener.
        (when (and (> orig ob) (< orig ce))
          (setq target ob))
        (goto-char target)
        (cons (point) d)))))

;; ── Jump-to-match: orchestration ──

(defun helixel--jump-to-match-core ()
  "Core match-jump logic, assuming point is already positioned.
Tries strategies in order:
  1. Known pair delimiter (when point is on/afer a delimiter)
  2. Syntax-table (standard Emacs bracket pairs)
  3. XML/HTML tag delimiter
  4. Fenced-block delimiter (org/markdown)

Returns (POINT . DELIMITER) on success — POINT is the jump
target, DELIMITER is the matched delimiter plist (nil for
syntax-table matches).  Returns nil when no match is found.

Leaves point unchanged on failure."
  (let* ((orig (point))
         (tables (helixel--jump-match--tables))
         (open->close (car tables))
         (close->open (cdr tables))
         (char-a (and (not (eobp)) (char-after)))
         (char-b (and (not (bobp)) (char-before)))
         (open-char (helixel--jump-match--open-char
                     char-a char-b open->close close->open))
         (close-char (and open-char
                          (gethash open-char open->close)))
         ;; Sandwich: between two close delimiters, step onto
         ;; the inner one so % targets the inner pair.
         (sandwich-p (and char-a char-b
                          (gethash char-a close->open)
                          (gethash char-b close->open))))
    (when sandwich-p (backward-char))
    (or (when (and open-char close-char
                   (not (eq open-char ?<)))
          (helixel--jump-via-pair open-char close-char char-a orig))
        (helixel--jump-via-syntax char-a char-b orig)
        (helixel--jump-via-tag orig)
        (helixel--jump-via-block orig)
        ;; All strategies failed — restore point.
        (progn (goto-char orig) nil))))

(defun helixel--close-chars ()
  "Return all close-delimiter chars from active surround-pairs.
A character is a close delimiter if it appears as the car of a
\(CLOSE . OPEN) entry or as both in an equal-pair entry."
  (helixel--active-delim-chars :close-only t))

(defun helixel--on-or-after-delim-p ()
  "Return non-nil if point is on or right after a non-quote delimiter.
Quote chars are excluded so \=`%' ignores them."
  (let ((delims (helixel--active-delim-chars :type :pair))
        (close  (helixel--active-delim-chars :type :pair :close-only t)))
    (or (and (not (eobp))
             (memq (char-after) delims))
        (and (not (bobp))
             (not (memq (char-after) delims))
             (memq (char-before) close)))))



(helixel-define-command helixel-jump-to-match
    (:category movement :subcat match)
  "Jump between matching delimiters.
When on or right after a delimiter, jump to its match.
When not on a delimiter, move to the enclosing opening delimiter
backward then jump to its match.  Only if nothing backward
does it try the core jump from the current position."
  (let (match-result)
    (cond
     ((helixel--on-or-after-delim-p)
      (unless (setq match-result (helixel--jump-to-match-core))
        (message "No matching bracket found")))
     ;; On a block delimiter line?  Try block/tag matching directly
     ;; so the block finder gets first chance (pair-char search
     ;; would otherwise steal focus, e.g. \=`#+end_src\=` near \=`)\=`).
     ((helixel--block-spec-at-point)
      (unless (setq match-result (helixel--jump-to-match-core))
        (message "No matching bracket found")))
     ((helixel--find-pair-char-dir 'backward)
      ;; Found a pair char backward - run core in save-excursion
      ;; to set ; mark-region, then STOP.  The user presses % again
      ;; from the delimiter to actually jump.
      (save-excursion (helixel--jump-to-match-core)))
     (t
      (unless (setq match-result (helixel--jump-to-match-core))
        (message "No matching bracket found"))))
    (when match-result
      (setq helixel--motion-extra
            (list :last-match-delimiter (cdr match-result))))))

(defvar-local helixel--pair-char-regex nil
  "Cached regexp for pair delimiter chars, or nil if not yet computed.
Set by `helixel--find-pair-char-dir'.")

(defvar-local helixel--pair-char-regex--mode nil
  "Major-mode for which `helixel--pair-char-regex' was computed.
Used by `helixel--find-pair-char-dir' to detect stale caches
after major-mode changes.")

(defun helixel--find-pair-char-dir (dir)
  "Search for nearest non-quote delimiter char in DIR (forward/backward).
On success, move point and return t.  On failure, return nil.

When DIR is `backward', first tries to find the ENCLOSING open
delimiter via `syntax-ppss' — this moves to the opening paren of
the form that contains point (like \\[backward-up-list]), instead of
finding a close delimiter of an inner form.  Falls back to regex-based
search when the enclosing depth is zero.  The regex backward search
is bounded by the previous blank line.

Forward search has no bound (nil).
Caches the regexp in `helixel--pair-char-regex' for performance."
  ;; When searching backward and we're inside a paren structure, use
  ;; syntax-ppss to jump directly to the enclosing open delimiter.
  ;; This is more useful than finding the nearest delimiter (which is
  ;; often a close-paren of an inner form).
  (or (and (eq dir 'backward)
           (let* ((ppss (syntax-ppss))
                  (depth (nth 0 ppss))
                  (open-pos (nth 1 ppss)))
             (and (> depth 0) open-pos
                  (progn (goto-char open-pos) t))))
      ;; Fall back to regex search when enclosing depth is zero.
      (when (or (null helixel--pair-char-regex)
                (not (eq major-mode helixel--pair-char-regex--mode)))
        (when-let* ((chars (helixel--active-delim-chars :type :pair)))
          (setq helixel--pair-char-regex
                (regexp-opt (mapcar #'char-to-string chars))
                helixel--pair-char-regex--mode major-mode))
        nil)
      (when helixel--pair-char-regex
        (if (eq dir 'forward)
            (when (re-search-forward helixel--pair-char-regex nil t)
              (goto-char (match-beginning 0)))
          (let ((bound (save-excursion
                         (when (re-search-backward "^[ \t]*$" nil t)
                           (line-beginning-position 2)))))
            (when (re-search-backward helixel--pair-char-regex bound t)
              (goto-char (match-beginning 0))))))))

;; ── One-level outward navigation (unified for forward/backward) ──

(defun helixel--delimiter-outer-target (d backward-p)
  "Return the outer target position for delimiter D.
Calls `helixel-delimiter-bounds-flat' to locate the enclosing pair.
BACKWARD-P non-nil → return opener (ob).
nil → return closer (ce).
Returns nil when no enclosing pair is found."
  (pcase-let* ((`(,ob ,_oe ,_cb ,ce)
                (helixel-delimiter-bounds-flat d)))
    (if backward-p ob ce)))

(defun helixel--up-list-once (dir &optional delim)
  "Move one nesting level outward in DIR (:backward or :forward).
DELIM is the delimiter plist to use for the outward lookup.
When nil, falls back to `helixel--last-motion-cmd's
:last-match-delimiter entry.  If neither is available, uses raw
`up-list'.  Sets mark-region for \\[helixel-action-cycle] support.
Returns t on success, nil (point unchanged) on failure.

Outward candidates are collected from four sources:
  1. stored delimiter (from \=`%' recording) - always wins if available
  2. raw \=`up-list' (parent pair of any bracket type)
  3. block delimiter (#+begin_src / #+end_src etc.)
  4. tag delimiter (XML/HTML)

The candidate closest to the original position wins, so
\\[helixel-repeat-last-motion] naturally expands layer-by-layer
from innermost to
outermost, whether the enclosing structure is a bracket pair or
a fenced block."
  (let* ((backward-p (eq dir :backward))
         (orig (point))
         (d (or delim
                (and helixel--last-motion-cmd
                     (helixel--last-motion-last-match-delimiter
                      helixel--last-motion-cmd))))
         (search-pos
          (save-excursion
            (helixel--step-off-delimiter)
            (point)))
         target)
    ;; Stored delimiter (from %) always wins.
    (setq target (save-excursion
                   (goto-char search-pos)
                   (cond
                    ((and d (eq (helixel-delimiter-type d) :pair))
                     (helixel--up-via-syntax-table d backward-p))
                    ((and d (helixel-delimiter-type d))
                     (helixel--up-via-bounds d backward-p)))))
    ;; Closest of the remaining candidates when stored delimiter
    ;; gives no target.
    (unless target
      (let ((raw (save-excursion
                   (goto-char search-pos)
                   (helixel--up-raw backward-p)))
            (block
             (helixel--with-debug-log up-multi-block
               (let ((helixel--block-no-bracket-fallback t))
                 (save-excursion
                   (goto-char search-pos)
                   (when-let* ((tgt (helixel--delimiter-outer-target
                                     (helixel-make-block-delimiter)
                                     backward-p)))
                     (cons (abs (- tgt orig)) tgt))))))
            (tag
             (helixel--with-debug-log up-multi-tag
               (save-excursion
                 (goto-char search-pos)
                 (when-let* ((tgt (helixel--delimiter-outer-target
                                   (helixel-make-tag-delimiter)
                                   backward-p)))
                   (cons (abs (- tgt orig)) tgt))))))
        ;; Pick the closest (lowest distance) valid candidate.
        (let ((best (car (sort (delq nil (list raw block tag))
                               (lambda (a b)
                                 (let ((da (if (consp a) (car a)
                                             (abs (- a orig))))
                                       (db (if (consp b) (car b)
                                             (abs (- b orig)))))
                                   (< da db)))))))
          (setq target (if (consp best) (cdr best) best)))))
    (if target
        (progn (goto-char target)
               ;; Run core to set mark-region for ; support.
               (save-excursion (helixel--jump-to-match-core))
               t)
      (goto-char orig)
      nil)))


(defun helixel--step-off-delimiter ()
  "If point is on a delimiter, step inside the pair.
Stepping direction depends only on whether the char at point
is a close or open delimiter."
  (when (memq (char-after) (helixel--pair-chars))
    (if (memq (char-after) (helixel--close-chars))
        (backward-char)
      (forward-char))))

(defun helixel--up-via-syntax-table (d backward-p)
  "Use raw `up-list' with temp syntax-table for BACKWARD-P pair D.
Returns point on success, nil when no parent pair exists.
For backward, two `up-list -1' calls (exit child, exit parent),
unless `backward-char' lands on an open delimiter — in that case
we are already at the parent opener (consecutive `((' case) and
the second `up-list -1' would overshoot.
For forward (from at-ce or inside a pair), one `up-list 1' suffices.
Returns nil if forward lands at eob (no parent)."
  (let* ((open (helixel-delimiter-open d))
         (close (helixel-delimiter-close d))
         forward-sexp-function)
    (helixel--with-debug-log up-via-syntax
      (with-syntax-table (copy-syntax-table (syntax-table))
        (modify-syntax-entry open (format "(%c" close))
        (modify-syntax-entry close (format ")%c" open))
        (up-list (if backward-p -1 1))
        (when backward-p
          (unless (bobp)
            (backward-char)
            (unless (eq (char-after) open)
              (up-list -1))))
        (if (and (not backward-p) (eobp))
            nil
          (point)))
      (error nil))))

(defun helixel--up-via-bounds (d backward-p)
  "Use `helixel-delimiter-bounds-flat' on D to locate parent pair.
BACKWARD-P controls direction."
  (if backward-p
      (pcase-let* ((`(,ob ,_oe ,_cb ,_ce)
                    (helixel-delimiter-bounds-flat d))
                   (open (helixel-delimiter-open d)))
        ;; When ob is at the buffer start there is no outer pair -
        ;; return ob itself (the opener of the outermost enclosing pair).
        (if (> ob (point-min))
            (progn (goto-char (1- ob))
                   (if (eq (char-after) open)
                       (point)  ; already at parent opener (consecutive '((')
                     (car (helixel-delimiter-bounds-flat d))))
          ob))
    ;; Go before the current pair's open so the next lookup
    ;; finds the enclosing (parent) pair, not the current one.
    (pcase-let* ((`(,ob ,_oe ,_cb ,ce)
                  (helixel-delimiter-bounds-flat d)))
      (if (> ob (point-min))
          (progn (goto-char (1- ob))
                 (helixel--with-debug-log up-via-bounds-nth
                   (nth 3 (helixel-delimiter-bounds-flat d))
                   (error ce)))
        ce))))

(defun helixel--up-raw (backward-p)
  "Move up two levels outward from the current list.
Works in BACKWARD-P direction, unless `backward-char' lands on
an open delimiter (consecutive `((' case), in which case we are
already at the parent opener.
If BACKWARD-P is non-nil, move backward; otherwise forward.
Returns point on success, nil when no parent pair exists."
  (helixel--with-debug-log up-raw
    (progn
      (up-list (if backward-p -1 1))
      (unless (if backward-p (bobp) (eobp))
        (if backward-p (backward-char) (forward-char)))
      (unless (and backward-p
                   (not (bobp))
                   (memq (char-after) (helixel--pair-chars))
                   (not (memq (char-after) (helixel--close-chars))))
        (up-list (if backward-p -1 1)))
      (unless backward-p (backward-char))
      (point))
    (error nil)))

(defun helixel--motion-skip-past (motion)
  "Advance point past the current boundary for MOTION's subcat.

For paragraph/sentence/function: skips past newline/whitespace.
For other subcats (match handled by dedicated repeater, pair by
its own repeater): no-op.  Skip-past is best-effort.

MOTION is a `helixel--last-motion' struct."
  (let ((sub (helixel--last-motion-subcat motion))
        (dir (helixel--last-motion-dir motion)))
    (condition-case nil
        (pcase sub
          ((or 'paragraph 'sentence 'function)
           (when dir
             (if (eq dir 'forward)
                 (progn (forward-char)
                        (skip-chars-forward " \t\n\r"))
               (progn (backward-char)
                      (skip-chars-backward " \t\n\r")))))
          (_ nil))
      (scan-error
       ;; Skip-past is best-effort; leave point unchanged.
       nil))))

(helixel-define-command helixel-forward-match
    (:category movement :subcat match)
  "Move to the closer of the enclosing parent pair."
  (unless (helixel--up-list-once :forward)
    (message "No enclosing bracket")))

(helixel-define-command helixel-backward-match
    (:category movement :subcat match)
  "Move to the opener of the enclosing parent pair."
  (unless (helixel--up-list-once :backward)
    (message "No enclosing bracket")))

(defsubst helixel--motion-eff-cmd (cmd rec)
  "Compute the effective CMD for REC's motion repeat.
Respects `helixel--motion-permanent-flip'."
  (if helixel--motion-permanent-flip
      (or (helixel--last-motion-reverse-command rec)
          (helixel--motion-reverse-lookup cmd)
          cmd)
    cmd))

(defun helixel--motion-invoke (rec effective-cmd orig)
  "Invoke EFFECTIVE-CMD with REC's prefix arg, restoring ORIG on error."
  (unless (commandp effective-cmd)
    (user-error "No motion command to repeat"))
  (let ((current-prefix-arg (helixel--last-motion-prefix-arg rec)))
    (condition-case err
        (call-interactively effective-cmd)
      (user-error
       (goto-char orig)
       (user-error (cadr err))))))

(defun helixel--repeat-pair-motion (rec)
  "Replay a pair delimiter motion (] [ } {) from REC.
For backward motions: steps to before the current pair so the
re-executed command finds the previous pair.
For forward motions: no skip-past needed — `bounds-next' handles
one-level stepping inherently.
On user-error restores point so a failing repeat doesn't strand
the cursor."
  (let* ((cmd (helixel--last-motion-command rec))
         (dir (helixel--last-motion-dir rec))
         (effective-cmd (helixel--motion-eff-cmd cmd rec))
         (orig (point)))
    ;; Backward skip-past: step inside current pair, then to (1- ob)
    ;; so bounds-previous finds the previous (parent) pair.
    (unless (eq dir 'forward)
      (when-let* ((d (funcall (helixel--last-motion-delim rec))))
        (when-let* ((adj (helixel-delimiter-adjust-for-jump d)))
          (funcall adj))
        (helixel--step-off-delimiter)
        (condition-case _err
            (let ((flat (helixel-delimiter-bounds-flat d)))
              (goto-char (max (point-min)
                              (1- (nth 0 flat))))
              (skip-chars-backward " \t\n\r"))
          (error
           (goto-char orig)))))
    (helixel--motion-invoke rec effective-cmd orig)))

;; Motion repeaters registered via `helixel-register-motion-repeater'

(defun helixel--repeat-match-motion (rec)
  "Replay a match (%) outward motion from REC.
Uses the stored delimiter from the original % jump for precise
outward navigation via `helixel--up-list-once'.

Opens tracking before the jump so `helixel--up-list-once' can
set `:mark-region' on the live action and the committed event
appears in the action ring.  This makes
\\[helixel-action-cycle] after \\[helixel-repeat-last-motion]
select the full span of the enclosing pair."
  (let* ((dir (helixel--last-motion-dir rec))
         (delim (helixel--last-motion-last-match-delimiter rec))
         (outward (if (eq dir 'forward) :forward :backward)))
    (helixel--tracking-open 'movement 'match)
    (unwind-protect
        (unless (helixel--up-list-once outward delim)
          (message "No enclosing bracket"))
      (unless (helixel-replaying-p)
        (helixel--action-commit)))))

(defun helixel--repeat-movement-motion (rec)
  "Replay a general movement motion from REC.
Skips past the current boundary via `helixel--motion-skip-past'
then re-invokes the original command with the recorded prefix arg.
On user-error restores point to before skip-past so a failing
\\[helixel-repeat-last-motion] doesn't leave the cursor stranded."
  (let* ((cmd (helixel--last-motion-command rec))
         (orig (point))
         (effective-cmd (helixel--motion-eff-cmd cmd rec)))
    (helixel--motion-skip-past rec)
    (helixel--motion-invoke rec effective-cmd orig)))

;; Register: specific subcats before general fallback.
;; `push' adds to the front; the lookup scans sequentially, so
;; specific entries are found before the nil-subcat fallback.
(helixel-register-motion-repeater 'movement nil
                                  #'helixel--repeat-movement-motion)
(helixel-register-motion-repeater 'movement 'match
                                  #'helixel--repeat-match-motion)
(helixel-register-motion-repeater 'movement 'pair
                                  #'helixel--repeat-pair-motion)

(helixel-define-command helixel-go-beginning-buffer
    (:category movement :subcat goto)
  (if current-prefix-arg
      (let ((n (prefix-numeric-value current-prefix-arg)))
        (goto-char (point-min))
        (forward-line (1- n)))
    (call-interactively #'beginning-of-buffer)))

;; ── Line / Rect selection ──

(defun helixel--line-end-or-invisible ()
  "Move to end of line, expanding past adjacent invisible text if enabled."
  (if (helixel--invisible-effective)
      (progn (end-of-line)
             (while (and (not (eobp))
                         (invisible-p (1+ (point)))
                         ;; When at EOL, expand into the next line only
                         ;; if it's fully invisible (not just an
                         ;; invisible prefix like vc-annotate).
                         ;; Mid-line always expands (same line).
                         (or (not (eolp))
                             (save-excursion
                               (goto-char (1+ (point)))
                               (invisible-p (line-end-position)))))
               (goto-char (1+ (point)))
               (let ((invis-end (if (get-text-property (point) 'invisible)
                                    (next-single-property-change
                                     (point) 'invisible nil (point-max))
                                  (next-overlay-change (point)))))
                 (goto-char (max (point-min) (1- invis-end)))
                 (end-of-line))))
    (end-of-line)))

(defun helixel--line-beginning-or-invisible ()
  "Move to beginning of line, expanding past invisible text if enabled."
  (beginning-of-line)
  (when (helixel--invisible-effective)
    (let ((opoint (point)))
      (while (and (not (bobp)) (invisible-p (1- (point))))
        (goto-char
         (if (get-text-property (1- (point)) 'invisible)
             (or (previous-single-property-change
                  (point) 'invisible (point-min))
                 (previous-overlay-change (point))))))
      (unless (bolp) (goto-char opoint)))))

(defun helixel-toggle-invisible ()
  "Toggle `helixel-invisible'.
Cycles \='auto → nil → t → \='open → \='auto."
  (interactive)
  (setq helixel-invisible
        (pcase helixel-invisible
          ('auto nil)
          ('nil t)
          ('t 'open)
          ('open 'auto)
          (_ nil)))
  (message "helixel: line expand invisible %s"
           (pcase helixel-invisible
             ('auto "auto")
             ('nil "off")
             ('open "open")
             (_ "on"))))

(defun helixel--extend-line-in-dir (dir)
  "Extend or shrink a linewise selection by one line in direction DIR.

DIR is `forward' (point moves down) or `backward' (point moves up).

At a 1-line boundary where point is on the wrong side for DIR
\(shrunk to a single line), exchanges point and mark to cross over.
Otherwise point moves in DIR:
- If the move would go toward mark it shrinks.
- If the move would go away from mark it extends.

The stored `:dir' in the selection context determines the direction;
after -x'/-X' flips `:dir', subsequent x'/X' presses follow the
new direction."
  (if (= (line-number-at-pos) (line-number-at-pos (mark)))
      ;; Same line: cross over only when point is on the wrong side
      ;; (i.e. we shrank to the boundary).  When point is on the
      ;; extend side (fresh or extended 1-line selection), extend.
      (if (or (and (eq dir 'forward) (< (point) (mark)))
              (and (eq dir 'backward) (> (point) (mark))))
          ;; Wrong side: cross over to the other side.
          (exchange-point-and-mark)
        ;; Extend side: move normally.
        (if (eq dir 'forward)
            (progn (forward-line 1) (helixel--line-end-or-invisible))
          (progn (forward-line -1) (helixel--line-beginning-or-invisible))))
    (if (eq dir 'forward)
        ;; Move point DOWN.
        (if (<= (point) (mark))
            ;; Point at or above mark: shrink from top.
            (progn (forward-line 1) (helixel--line-beginning-or-invisible))
          ;; Point below mark: extend from bottom.
          (progn (forward-line 1) (helixel--line-end-or-invisible)))
      ;; Move point UP (dir = backward).
      (if (>= (point) (mark))
          ;; Point at or below mark: shrink from bottom.
          (progn (forward-line -1) (helixel--line-end-or-invisible))
        ;; Point above mark: extend from top.
        (progn (forward-line -1) (helixel--line-beginning-or-invisible))))))

(helixel-define-command helixel-select-line
    (:category movement :subcat lineselect
               :params (&optional count) :clear-highlights nil)
  (interactive "p")
  (let* ((n (or count 1))
         (abs-n (abs n))
         (flip-p (< n 0))
         (current-prefix-arg nil))
    ;; Flip permanent direction on negative prefix (like N for search).
    (when (and flip-p helixel--pending-sel
               (eq (helixel-sel-kind helixel--pending-sel) 'line))
      (when-let* ((fn (helixel--kind-flip-dir-fn 'line)))
        (helixel--sel-push (funcall fn helixel--pending-sel))))
    (let ((extending (and (region-active-p)
                          (eq (helixel--sel-type) 'line))))
      (if extending
          ;; Extend/shrink in the stored direction.
          (let ((dir (helixel-sel-line-dir helixel--pending-sel)))
            (dotimes (_ abs-n)
              (helixel--extend-line-in-dir dir)))
        ;; New selection (forward: point at bottom, mark at top).
        (beginning-of-line)
        (push-mark-command t t)
        (helixel--line-end-or-invisible)
        (dotimes (_ (1- abs-n))
          (forward-line 1)
          (helixel--line-end-or-invisible)))
      (let* ((new-count (if extending
                            (max 1 (1+ (- (line-number-at-pos (region-end))
                                          (line-number-at-pos
                                           (region-beginning)))))
                          abs-n))
             (dir (if extending
                      (helixel-sel-line-dir helixel--pending-sel)
                    'forward)))
        (helixel--push-selection 'line `(:count ,new-count :dir ,dir))))))

(helixel-define-command helixel-select-line-up
    (:category movement :subcat lineselect
               :params (&optional count) :clear-highlights nil)
  (interactive "p")
  (let* ((n (or count 1))
         (abs-n (abs n))
         (flip-p (< n 0))
         (current-prefix-arg nil))
    ;; Flip permanent direction on negative prefix (like N for search).
    (when (and flip-p helixel--pending-sel
               (eq (helixel-sel-kind helixel--pending-sel) 'line))
      (when-let* ((fn (helixel--kind-flip-dir-fn 'line)))
        (helixel--sel-push (funcall fn helixel--pending-sel))))
    (let ((extending (and (region-active-p)
                          (eq (helixel--sel-type) 'line))))
      (if extending
          ;; Extend/shrink in the stored direction.
          (let ((dir (helixel-sel-line-dir helixel--pending-sel)))
            (dotimes (_ abs-n)
              (helixel--extend-line-in-dir dir)))
        ;; New selection (backward: point at top, mark at bottom).
        (helixel--line-end-or-invisible)
        (push-mark-command t t)
        (helixel--line-beginning-or-invisible)
        (dotimes (_ (1- abs-n))
          (forward-line -1)
          (helixel--line-beginning-or-invisible)))
      (let* ((new-count (if extending
                            (max 1 (1+ (- (line-number-at-pos (region-end))
                                          (line-number-at-pos
                                           (region-beginning)))))
                          abs-n))
             (dir (if extending
                      (helixel-sel-line-dir helixel--pending-sel)
                    'backward)))
        (helixel--push-selection 'line `(:count ,new-count :dir ,dir))))))

(helixel-define-command helixel-select-rectangle
    (:category movement :subcat rectselect
               :params (&optional count) :clear-highlights nil)
  (interactive "p")
  (let ((n (or count 1))
        (extending rectangle-mark-mode)
        (current-prefix-arg nil))
    (if extending
        (dotimes (_ n)
          (if (or (> (point) (mark))
                  (and (= (point) (mark))
                       (eq last-command 'helixel-select-rectangle)))
              (forward-line 1)
            (forward-line -1))
          (rectangle--reset-point-crutches))
      (push-mark (point) t t)
      (rectangle-mark-mode 1)
      (dotimes (_ (1- n))
        (forward-line 1)
        (rectangle--reset-point-crutches)))
    (let* ((prev-count (helixel-sel-count helixel--pending-sel))
           (new-count (if extending (+ prev-count n) n)))
      (helixel--push-selection 'rect `(:count ,new-count)))))


;; ── Line / Rect recreate functions ──
;; Used by `.` replay to rebuild linewise/rectangular selections.

(defun helixel--recreate-line (ctx)
  "Replay a linewise selection from CTX.
When :entry-kind is present (insert ops), position cursor
at the appropriate offset on the selected line:
  :entry-kind insert \=`region-beginning' + cursor-offset
  :entry-kind append \=`region-end' + cursor-offset
When :span is set, extends region back to the pre-recreate origin."
  (let ((n (helixel-sel-line-count ctx))
        (entry-kind (helixel-sel-entry-kind ctx)))
    (helixel--with-span ctx
      (if (eq (helixel-sel-line-dir ctx) 'backward)
          (helixel-select-line-up n)
        (helixel-select-line n))
      ;; Signal error when buffer is empty (nothing to select).
      ;; The strategy catches this to stop iteration.
      (when (and (bobp) (eobp))
        (user-error "No more targets")))
    (when entry-kind
      ;; Position cursor for key/text insertion.
      ;; Use region-beginning/region-end because helixel-select-line
      ;; leaves point on the LAST selected line, so
      ;; line-beginning-position/line-end-position would target
      ;; the wrong line for multi-line selections.
      (if (eq entry-kind 'append)
          (goto-char (region-end))
        (let ((rend (region-end)))
          (goto-char (region-beginning))
          ;; If point landed on the mark (zero-length region),
          ;; restore the visible region so the selection highlight
          ;; shows the full target range.
          (when (= (point) (mark))
            (set-mark rend))))
      (let ((off (helixel-sel-insert-cursor-offset ctx)))
        (when off (forward-char off))))))

(defun helixel--recreate-rect (ctx)
  "Replay a rectangular selection from CTX.
When :span is set, extends region back to the pre-recreate origin
without disturbing the rectangle's own mark.

NOTE: Does NOT use `helixel--with-span' because `push-mark' inside
`rectangle-mark-mode' behaves differently - we must deactivate the
rectangle mark, push the span origin, then reactivate.  The macro's
simple `push-mark' would interact poorly with the rect-mode mark."
  (let ((n (helixel-sel-rect-count ctx))
        (span-origin (when (helixel-sel-span-p ctx) (point))))
    (unless rectangle-mark-mode
      (push-mark (point) t t)
      (rectangle-mark-mode 1))
    (dotimes (_ (1- n))
      (forward-line 1)
      (rectangle--reset-point-crutches))
    (when span-origin
      (deactivate-mark)
      (push-mark span-origin t t)
      (activate-mark))))

(defun helixel--recreate-movement (ctx)
  "Replay movement selection from CTX.
By default, the region accumulates across all commands (visual-mode
behaviour for e.g. `v w w d .`).  When :normal-mode is non-nil in
CTX, each movement resets the selection (normal-mode behaviour).
When :span is set (from \\[helixel-action-cycle] push),
`normal-mode' is ignored so
\=`; d .' replays the full movement span correctly.
Signals `user-error' when point does not move (no more targets)."
  ;; :span forces visual-mode accumulation regardless of :normal-mode.
  ;; Enter visual state for accumulating movements so `clear-highlights'
  ;; in the funcall'd movement commands don't deactivate the region.
  (unless (and (helixel-sel-movement-normal-mode-p ctx)
               (not (helixel-sel-span-p ctx)))
    (setq helixel--current-state 'visual))
  (helixel--with-span ctx
    (let ((saved-pos (point)))
      (dolist (m (reverse (helixel-sel-movement-moves ctx)))
        (dotimes (_ (cdr m))
          (funcall (car m))))
      (when (= (point) saved-pos)
        (user-error "No more targets")))))


;; ── Line and movement advance functions (from helixel-repeat.el) ──

(defun helixel--repeat-advance-line (tx)
  "Advance TX past the current line target in selection's direction.
For append entry-kind (cursor at `region-end' after op), advance 1 line.
Otherwise advance by the selection count.
After advancing, recreates the line selection to position point
correctly (bol for insert, eol for append).  Returns nil at buffer edge.
Deactivates any prior region so `helixel-select-line-up' starts
fresh rather than extending a stale mark."
  (let* ((sel (helixel-action-sel tx))
         (dir (if (eq (helixel-sel-line-dir sel) 'backward) -1 1))
         (entry-kind (helixel-sel-entry-kind sel))
         (count (if (eq entry-kind 'append) 1
                  (helixel-sel-line-count sel)))
         (lines-left count))
    (while (and (> lines-left 0) (= (forward-line dir) 0))
      (unless (helixel--blank-line-p)
        (setq lines-left (1- lines-left))))
    (when (= lines-left 0)
      (deactivate-mark)
      (helixel--recreate-selection sel)
      t)))

;; ── Kind registrations ──

(helixel-register-kind line
  :sel-type 'line
  :ctx-schema '(:required (:count :dir) :optional (:entry-kind :span))
  :recreate #'helixel--recreate-line
  :advance  #'helixel--repeat-advance-line
  :all-buffer-fn #'helixel--all-buffer-line
  :all-dir-fn #'helixel--all-dir-line
  :flip-dir-fn (lambda (sel)
                 (helixel-sel-update-ctx
                  sel :dir (helixel--flip-dir
                            (helixel-sel-line-dir sel))))
  :display  "L")

(helixel-register-kind rect
  :sel-type 'rect
  :ctx-schema '(:required (:count) :optional ())
  :recreate #'helixel--recreate-rect
  :advance  nil
  :display  "R")

(helixel-register-kind movement
  :ctx-schema '(:required (:moves) :optional (:inline-advance :normal-mode))
  :recreate #'helixel--recreate-movement
  :advance  #'helixel--advance-by-recreate
  :flip-dir-fn (lambda (sel)
                 (helixel-sel-update-ctx
                  sel :moves
                  (mapcar (lambda (entry)
                            (let* ((cmd (car entry))
                                   (cnt (cdr entry))
                                   (rev (helixel--motion-reverse-lookup cmd)))
                              (cons (or rev cmd) cnt)))
                          (helixel-sel-movement-moves sel))))
  :display  (lambda (ctx)
              (let ((ms (helixel-sel-movement-moves ctx)))
                (let ((n (apply #'+ (mapcar #'cdr ms))))
                  (format "v%d" n)))))

;; ── Visual move tracking (from helixel-state.el) ──

(defun helixel--track-visual-move (cmd)
  "Append movement CMD to `helixel--pending-sel'.
Creates/updates a `helixel-sel' struct of kind `movement' whenever
a region is active - from visual mode or `normal-mode' movements that
created a selection (e.g. w, e, b).
No-op during dot-repeat replay, or when no region is active.

When `helixel--pending-sel' holds a non-movement kind (rect/line/
textobj), this function is a no-op — the selection type is preserved
for operators (d/y/c).  Such pending-sels appear after
`helixel-select-rectangle' or `helixel-select-line' followed by
basic motion commands (j/k) that are defined via
`helixel-define-movement' (which preserves the sel).
Word-movement commands (helixel--with-movement-surround) clear
non-movement sels, so nil is the only ctx possible there."
  (when (and (not (helixel-replaying-p))
             (use-region-p))
    (let* ((ctx helixel--pending-sel)
           (entry (cons cmd 1)))
      (cond
       ;; Update: extend existing movement sel.
       ((and ctx (eq (helixel-sel-kind ctx) 'movement))
        (let* ((moves (helixel-sel-movement-moves ctx))
               (last (car moves)))
          (if (and last (eq (car last) cmd))
              (setcdr last (1+ (cdr last)))
            (helixel--sel-push
             (helixel-sel-update-ctx ctx :moves
                                     (cons entry moves))))))
       ;; Create: first movement that made a region.
       ((null ctx)
        (helixel--sel-push
         (helixel-sel-create 'movement
                             `(:moves (,entry) :inline-advance t
                                      :normal-mode
                                      ,(eq helixel--current-state
                                           'normal)))))))))

(provide 'helixel-move)
;;; helixel-move.el ends here
