;;; helixel-move.el --- Move & sel commands  -*- lexical-binding: t; -*-

;; Copyright (C) 2025-2026  jixiuf

;; Author: jixiuf
;; Keywords: convenience
;; URL: https://github.com/jixiuf/helixel-mode

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:

;; Movement and selection commands for helixel-mode.
;;
;; Provides `helixel-define-movement' for wrapping built-in commands with
;; action tracking, plus hand-written word/WORD/symbol movement commands,
;; line/rectangle selection, surround-thing-at-point, and the line-wise
;; and rect-wise kill/yank helpers.
;;
;; Also houses `helixel--rect-change' and `helixel--rect-replay' for
;; rectangle-change-with-replay support, and `helixel--replace-region'
;; / `helixel-replace-char' for character replacement.

;;; Code:

(require 'cl-lib)
(require 'rect)
(require 'helixel-state)
(require 'helixel-macros)

(defvar helixel-block-textobj-alist)

;; Forward-declare from helixel-textobj.el (mutual deps via helixel-state).
(declare-function helixel--block-spec-at-point "helixel-textobj" ())

;; All-buffer/all-dir line handlers (defined in helixel-repeat.el).
(declare-function helixel--all-buffer-line "helixel-repeat"
                  (edit prefix))
(declare-function helixel--all-dir-line "helixel-repeat"
                  (edit))

(defmacro helixel-define-movement (name builtin type &rest options)
  "Define a movement command NAME wrapping BUILTIN with TYPE.

OPTIONS is a plist supporting:
  :advice              — inject :before advice instead of creating wrapper
  :clear-highlights BOOL — clear highlights before executing (default t)

Wrapper mode (default): delegates to `helixel-define-command'.
  (helixel-define-movement helixel-forward-char forward-char char)

Advice mode:
  (helixel-define-movement nil forward-char char :advice)

Without highlights clearing:
  (helixel-define-movement helixel-scroll-up scroll-up-command scroll
                        :clear-highlights nil)"
  (declare (indent 1))
  (let* ((advicep (plist-get options :advice))
         (clear (if (plist-member options :clear-highlights)
                    (plist-get options :clear-highlights)
                  t)))
    (if advicep
        `(advice-add #',builtin :before
                     (lambda (&rest _)
                       ,(format "Helixel %s movement advice." type)
                       (helixel--tracking-open 'movement ',type)
                       ,@(when clear
                           '((helixel--clear-highlights)))))
      `(helixel-define-command ,name
           (:category movement :subcat ,type
                      :clear-highlights ,clear)
         (call-interactively #',builtin)))))

(defmacro helixel-define-movements (&rest specs)
  "Register multiple movements from SPECS.
Each element of SPECS is a list of args for `helixel-define-movement'.

Example:
  (helixel-define-movements
    (helixel-forward-char forward-char char)
    (helixel-next-line next-line line))"
  `(progn
     ,@(mapcar (lambda (s) `(helixel-define-movement ,@s)) specs)))

;; ── Simple movement wrappers ──
;; Generated by helixel-define-movement for builtin commands that only need
;; action tracking + highlight clearing + call-interactively.

(helixel-define-movement helixel-backward-char backward-char char)
(helixel-define-movement helixel-forward-char forward-char char)
(helixel-define-movement helixel-next-line next-line line)
(helixel-define-movement helixel-previous-line previous-line line)
(helixel-define-movement helixel-go-beginning-line beginning-of-line goto)
(helixel-define-movement helixel-go-end-line end-of-line goto)
(helixel-define-movement helixel-go-first-nonwhitespace
  back-to-indentation goto)
(helixel-define-movement helixel-go-end-buffer end-of-buffer goto)
(helixel-define-movement helixel-scroll-up-command scroll-up-command scroll
                         :clear-highlights nil)
(helixel-define-movement helixel-scroll-down-command scroll-down-command scroll
                         :clear-highlights nil)

;; ── Word / WORD / Symbol movement ──

(defun helixel-surround-thing-at-point (&optional thing)
  "Construct a region around THING at point.

Argument THING must be one of the things identified by the package
thingatpt.  Defaults to \\='word."
  (let ((bounds (bounds-of-thing-at-point (or thing 'word))))
    (when bounds
      (set-mark (car bounds))
      (goto-char (cdr bounds))
      (activate-mark))))

(defmacro helixel--with-movement-surround (&rest body)
  "Create a region around movement defined in BODY.
If a region is already active, no new region is created.

Movement commands redefine the selection, so they reset
`helixel--raw-selection-type' to nil — a previous `line' / `rect'
label from `x' / `v' must not bleed into the new region (which
would make `y' tag the kill as line-wise even when the user
selected a word).

Note: `helixel-define-command' handles `clear-highlights'
and `track-visual-move'
automatically, so this macro only does `push-mark' + activate."
  `(let ((current (point)))
     ,@body
     (unless (use-region-p)
       (push-mark current t 'activate))
     (setq helixel--raw-selection-type nil)))

;; ── Word / WORD / symbol movement commands ──
;;
;; All twelve forward/backward × word/WORD/symbol × start/end commands
;; share the same body shape; we generate them via
;; `helixel--def-thing-move'.  Some `:side' values are NOT mechanical
;; (helixel-backward-WORD uses :a, helixel-backward-symbol-start uses
;; :a, helixel-backward-symbol-end uses :inner — preserved verbatim
;; from the original definitions).

(defmacro helixel--def-thing-move (name subcat thing fwd-fn sign side)
  "Define a thing-movement command.
NAME is the command symbol; SUBCAT the :subcat tag; THING the
thing category (`helixel-word' / -WORD / -symbol);
FWD-FN is one of `forward-beginning' / `forward-end' (interned
relative to `helixel--');  SIGN is +1 or -1; SIDE is :a or :inner."
  (let ((fn (intern (format "helixel--%s" fwd-fn))))
    `(helixel-define-command ,name
         (:category movement :subcat ,subcat
          :params (&optional count))
       (interactive "p")
       (helixel--with-movement-surround
        (,fn ',thing (* ,sign (or count 1))))
       (helixel--set-mark-region ',thing ,side))))

(helixel--def-thing-move helixel-forward-word-start
                         word helixel-word forward-beginning  1 :a)
(helixel--def-thing-move helixel-forward-word-end
                         word helixel-word forward-end        1 :inner)
(helixel--def-thing-move helixel-backward-word-start
                         word helixel-word forward-beginning -1 :inner)
(helixel--def-thing-move helixel-backward-word-end
                         word helixel-word forward-end       -1 :a)

(helixel--def-thing-move helixel-forward-WORD-start
                         WORD helixel-WORD forward-beginning  1 :a)
(helixel--def-thing-move helixel-forward-WORD-end
                         WORD helixel-WORD forward-end        1 :inner)
(helixel--def-thing-move helixel-backward-WORD
                         WORD helixel-WORD forward-beginning -1 :a)
(helixel--def-thing-move helixel-backward-WORD-end
                         WORD helixel-WORD forward-end       -1 :inner)

(helixel--def-thing-move helixel-forward-symbol-start
                         symbol helixel-symbol forward-beginning  1 :a)
(helixel--def-thing-move helixel-forward-symbol-end
                         symbol helixel-symbol forward-end        1 :inner)
(helixel--def-thing-move helixel-backward-symbol-start
                         symbol helixel-symbol forward-beginning -1 :a)
(helixel--def-thing-move helixel-backward-symbol-end
                         symbol helixel-symbol forward-end       -1 :inner)

(defmacro helixel--define-delimiter-movement (name outer-p forward-p
                                                   factory &rest factory-args)
  "Define a delimiter movement command NAME.
OUTER-P non-nil → outer (a), nil → inner (i).
FORWARD-P non-nil → forward-to-end (] }), nil → outward-to-open ([ {).
FACTORY is a function called with FACTORY-ARGS to produce the delimiter."
  (declare (indent defun))
  (let ((inner-p (not outer-p))
        (bounds-fn (if forward-p
                       'helixel--generic-bounds-next
                     'helixel--generic-bounds-at)))
    `(helixel-define-command ,name
         (:category movement :subcat pair :clear-highlights nil)
       (interactive)
       (deactivate-mark)
       (let* ((d (,factory ,@factory-args))
              (b (,bounds-fn d ,inner-p)))
         (when b
           (helixel--set-mark-region b)
           (let ((pos (if ,forward-p (cdr b) (car b))))
             (goto-char pos)))))))

;; ── Pair delimiters (parens, brackets, braces, angle, quotes) ──

(helixel--define-delimiter-movement helixel-outer-paren t nil
  helixel--make-pair-delimiter ?\( ?\))
(helixel--define-delimiter-movement helixel-next-paren-end t t
  helixel--make-pair-delimiter ?\( ?\))
(helixel--define-delimiter-movement helixel-inner-outer-paren nil nil
  helixel--make-pair-delimiter ?\( ?\))
(helixel--define-delimiter-movement helixel-inner-next-paren-end nil t
  helixel--make-pair-delimiter ?\( ?\))

(helixel--define-delimiter-movement helixel-outer-bracket t nil
  helixel--make-pair-delimiter ?\[ ?\])
(helixel--define-delimiter-movement helixel-next-bracket-end t t
  helixel--make-pair-delimiter ?\[ ?\])
(helixel--define-delimiter-movement helixel-inner-outer-bracket nil nil
  helixel--make-pair-delimiter ?\[ ?\])
(helixel--define-delimiter-movement helixel-inner-next-bracket-end nil t
  helixel--make-pair-delimiter ?\[ ?\])

(helixel--define-delimiter-movement helixel-outer-brace t nil
  helixel--make-pair-delimiter ?{ ?})
(helixel--define-delimiter-movement helixel-next-brace-end t t
  helixel--make-pair-delimiter ?{ ?})
(helixel--define-delimiter-movement helixel-inner-outer-brace nil nil
  helixel--make-pair-delimiter ?{ ?})
(helixel--define-delimiter-movement helixel-inner-next-brace-end nil t
  helixel--make-pair-delimiter ?{ ?})

(helixel--define-delimiter-movement helixel-outer-angle t nil
  helixel--make-pair-delimiter ?< ?>)
(helixel--define-delimiter-movement helixel-next-angle-end t t
  helixel--make-pair-delimiter ?< ?>)
(helixel--define-delimiter-movement helixel-inner-outer-angle nil nil
  helixel--make-pair-delimiter ?< ?>)
(helixel--define-delimiter-movement helixel-inner-next-angle-end nil t
  helixel--make-pair-delimiter ?< ?>)

(helixel--define-delimiter-movement helixel-outer-double-quote t nil
  helixel--make-pair-delimiter ?\" ?\")
(helixel--define-delimiter-movement helixel-next-double-quote-end t t
  helixel--make-pair-delimiter ?\" ?\")
(helixel--define-delimiter-movement helixel-inner-outer-double-quote nil nil
  helixel--make-pair-delimiter ?\" ?\")
(helixel--define-delimiter-movement helixel-inner-next-double-quote-end nil t
  helixel--make-pair-delimiter ?\" ?\")

(helixel--define-delimiter-movement helixel-outer-single-quote t nil
  helixel--make-pair-delimiter ?' ?')
(helixel--define-delimiter-movement helixel-next-single-quote-end t t
  helixel--make-pair-delimiter ?' ?')
(helixel--define-delimiter-movement helixel-inner-outer-single-quote nil nil
  helixel--make-pair-delimiter ?' ?')
(helixel--define-delimiter-movement helixel-inner-next-single-quote-end nil t
  helixel--make-pair-delimiter ?' ?')

(helixel--define-delimiter-movement helixel-outer-back-quote t nil
  helixel--make-pair-delimiter ?` ?`)
(helixel--define-delimiter-movement helixel-next-back-quote-end t t
  helixel--make-pair-delimiter ?` ?`)
(helixel--define-delimiter-movement helixel-inner-outer-back-quote nil nil
  helixel--make-pair-delimiter ?` ?`)
(helixel--define-delimiter-movement helixel-inner-next-back-quote-end nil t
  helixel--make-pair-delimiter ?` ?`)

;; ── Tag delimiter movement ──

(helixel--define-delimiter-movement helixel-outer-tag t nil
  helixel--make-tag-delimiter)
(helixel--define-delimiter-movement helixel-next-tag-end t t
  helixel--make-tag-delimiter)
(helixel--define-delimiter-movement helixel-inner-outer-tag nil nil
  helixel--make-tag-delimiter)
(helixel--define-delimiter-movement helixel-inner-next-tag-end nil t
  helixel--make-tag-delimiter)

;; ── Block delimiter movement ──

(helixel--define-delimiter-movement helixel-outer-block t nil
  helixel--make-block-delimiter)
(helixel--define-delimiter-movement helixel-next-block-end t t
  helixel--make-block-delimiter)
(helixel--define-delimiter-movement helixel-inner-outer-block nil nil
  helixel--make-block-delimiter)
(helixel--define-delimiter-movement helixel-inner-next-block-end nil t
  helixel--make-block-delimiter)

;; `helixel--generic-bounds-at' / `helixel--generic-bounds-next'
;; are defined in helixel-core.el.

;; ── Paragraph / sentence / function movement commands ──
;; All twelve commands here use :side :a (verbatim from originals).

(helixel--def-thing-move helixel-forward-paragraph-start
                         paragraph helixel-paragraph forward-beginning  1 :a)
(helixel--def-thing-move helixel-backward-paragraph-start
                         paragraph helixel-paragraph forward-beginning -1 :a)
(helixel--def-thing-move helixel-forward-paragraph-end
                         paragraph helixel-paragraph forward-end        1 :a)
(helixel--def-thing-move helixel-backward-paragraph-end
                         paragraph helixel-paragraph forward-end       -1 :a)

(helixel--def-thing-move helixel-forward-sentence-end
                         sentence helixel-sentence forward-end          1 :a)
(helixel--def-thing-move helixel-backward-sentence-start
                         sentence helixel-sentence forward-beginning   -1 :a)
(helixel--def-thing-move helixel-forward-sentence-start
                         sentence helixel-sentence forward-beginning    1 :a)
(helixel--def-thing-move helixel-backward-sentence-end
                         sentence helixel-sentence forward-end         -1 :a)

(helixel--def-thing-move helixel-forward-function-end
                         function helixel-function forward-end          1 :a)
(helixel--def-thing-move helixel-backward-function-start
                         function helixel-function forward-beginning   -1 :a)
(helixel--def-thing-move helixel-forward-function-start
                         function helixel-function forward-beginning    1 :a)
(helixel--def-thing-move helixel-backward-function-end
                         function helixel-function forward-end         -1 :a)

(defun helixel--jump-target-for-delimiter (d orig &optional no-close-backoff
                                                mark-thing)
  "Try to find a jump target using delimiter D.
ORIG is the original point.  Returns (TARGET . (OB . CE)) on success,
or nil if no enclosing pair found.
When NO-CLOSE-BACKOFF is non-nil, passed through to `helixel-delimiter-bounds'.
When MARK-THING is non-nil, stores bounds as markers in the
live event's \=:mark-region for `\;' marking."
  (save-excursion
    (when-let* ((adj (helixel-delimiter-adjust-for-jump d)))
      (funcall adj))
    (condition-case nil
        (pcase-let* ((`(,ob ,_oe ,_cb ,ce)
                      (helixel-delimiter-bounds-flat d no-close-backoff)))
          (when mark-thing
            (helixel--set-mark-region (cons ob ce)))
          (cons (if (<= (abs (- orig ob)) (abs (- orig ce))) ce ob)
                (cons ob ce)))
      (error nil))))

(defun helixel--jump-syntax-table (char-a char-b orig)
  "Try to jump via syntax-table from any position.
Returns a cons (TARGET . (OB . CE)) on success, or nil.
CHAR-A and CHAR-B are as in `helixel-jump-to-match'.
ORIG is the original point before jumping."
  (save-excursion
    (condition-case nil
        (let ((match-end
               (progn
                 (cond
                  ((and char-a (memq (char-syntax char-a) '(4 ?\( ?\))))
                   (forward-list 1))
                  ((and char-b (memq (char-syntax char-b) '(5 ?\( ?\))))
                   (forward-list -1))
                  (t
                   (up-list 1)))
                 (point))))
          (goto-char match-end)
          (condition-case nil
              (backward-list 1)
            (error nil))
          (let ((b (if (>= match-end (point)) (point) match-end))
                (e (if (>= match-end (point)) match-end (point))))
            (helixel--set-mark-region (cons b e))
            (cons (if (<= (abs (- orig b)) (abs (- orig e))) e b)
                  (cons b e))))
      (error nil))))

(helixel-define-command helixel-jump-to-match
    (:category movement :subcat match)
  "Jump between matching delimiters.
Uses the textobj delimiter protocol to find the matching end of
any pair (parens, brackets, braces, quotes, angle-brackets),
XML tags, or org/markdown blocks.  Falls back to syntax-table
for unmatched bracket characters."
  (let* ((orig (point))
         ;; Build canonical open→close and close→open maps.
         (open->close
          (let ((map (make-hash-table)))
            (dolist (pair helixel--surround-pairs)
              (let ((a (car pair)) (b (cdr pair)))
                (when (<= a b)            ; <= so quotes (a=b) are included
                  (puthash a b map))))
            map))
         (close->open
          (let ((map (make-hash-table)))
            (maphash (lambda (k v) (puthash v k map)) open->close)
            map))
         (char-a (and (not (eobp)) (char-after)))
         (char-b (and (not (bobp)) (char-before)))
         (open-char
          (or (and char-a (gethash char-a open->close) char-a)
              (and char-b (gethash char-b open->close) char-b)
              (and char-a (gethash char-a close->open))
              (and char-b (gethash char-b close->open))))
         (close-char (and open-char (gethash open-char open->close))))
    (catch 'done
      ;; ── Pair delimiters (parens, brackets, braces, quotes) ──
      ;; Angle brackets (< >) are excluded — handled as tags below.
      ;; Skip pair handling when on a block delimiter line
      ;; (e.g. markdown ``` fences — backtick is also a quote char).
      (when (and open-char close-char (not (eq open-char ?<))
                 (not (and (eq open-char ?\`)
                           (helixel--block-spec-at-point))))
        (let* ((d (helixel--make-pair-delimiter open-char close-char))
               (on-opener (and char-a (eq char-a open-char)))
               (equalp (eq open-char close-char)))
          (when on-opener (forward-char))
          (when-let* ((result (helixel--jump-target-for-delimiter
                              d orig (and on-opener equalp) t)))
            (goto-char (car result))
            (throw 'done t))))
      ;; ── Syntax-table fallback (innermost bracket from any pos) ──
      (when-let* ((result (helixel--jump-syntax-table char-a char-b orig)))
        (goto-char (car result))
        (throw 'done t))
      ;; ── Tags (XML/HTML tags) ──
      (when-let* ((d (helixel--make-tag-delimiter))
                  (result (helixel--jump-target-for-delimiter
                           d orig nil 'helixel-mark-a-tag)))
        (goto-char (car result))
        (throw 'done t))
      ;; ── Blocks (org, markdown) ──
      (when-let* ((d (helixel--make-block-delimiter))
                  (result (helixel--jump-target-for-delimiter
                           d orig)))
        (goto-char (car result))
        (throw 'done t))
      ;; ── Syntax-table fallback (final safety net) ──
      (when-let* ((result (helixel--jump-syntax-table char-a char-b orig)))
        (goto-char (car result))
        (throw 'done t)))
    (when (= (point) orig)
      (message "No matching bracket found"))))

(helixel-define-command helixel-go-beginning-buffer
    (:category movement :subcat goto)
  (if current-prefix-arg
      (let ((n (prefix-numeric-value current-prefix-arg)))
        (goto-char (point-min))
        (forward-line (1- n)))
    (call-interactively #'beginning-of-buffer)))

(helixel-define-command helixel-goto-line
    (:category movement :subcat goto :params (&optional arg))
  (interactive "P")
  (let ((n (if arg
               (prefix-numeric-value arg)
             (goto-line-read-args))))
    (goto-char (point-min))
    (forward-line (1- n))))

;; ── Line / Rect selection ──

(defun helixel--extend-line-in-dir (dir)
  "Extend or shrink a linewise selection by one line in direction DIR.

DIR is `forward' (point moves down) or `backward' (point moves up).

At a 1-line boundary where point is on the wrong side for DIR
\(shrunk to a single line), exchanges point and mark to cross over.
Otherwise point moves in DIR:
- If the move would go toward mark it shrinks.
- If the move would go away from mark it extends.

The stored `:dir' in the selection context determines the direction;
after `-x'/`-X' flips `:dir', subsequent `x'/`X' presses follow the
new direction."
  (if (= (line-number-at-pos) (line-number-at-pos (mark)))
      ;; Same line: cross over only when point is on the wrong side
      ;; (i.e. we shrank to the boundary).  When point is on the
      ;; extend side (fresh or extended 1-line selection), extend.
      (if (or (and (eq dir 'forward) (< (point) (mark)))
              (and (eq dir 'backward) (> (point) (mark))))
          ;; Wrong side: cross over to the other side.
          (exchange-point-and-mark)
        ;; Extend side: move normally.
        (if (eq dir 'forward)
            (progn (forward-line 1) (end-of-line))
          (progn (forward-line -1) (beginning-of-line))))
    (if (eq dir 'forward)
        ;; Move point DOWN.
        (if (<= (point) (mark))
            ;; Point at or above mark: shrink from top.
            (progn (forward-line 1) (beginning-of-line))
          ;; Point below mark: extend from bottom.
          (progn (forward-line 1) (end-of-line)))
      ;; Move point UP (dir = backward).
      (if (>= (point) (mark))
          ;; Point at or below mark: shrink from bottom.
          (progn (forward-line -1) (end-of-line))
        ;; Point above mark: extend from top.
        (progn (forward-line -1) (beginning-of-line))))))

(helixel-define-command helixel-select-line
    (:category movement :subcat lineselect
               :params (&optional count) :clear-highlights nil)
  (interactive "p")
  (let* ((n (or count 1))
         (abs-n (abs n))
         (flip-p (< n 0))
         (current-prefix-arg nil))
    ;; Flip permanent direction on negative prefix (like `N' for search).
    (when (and flip-p helixel--pending-sel
               (eq (helixel-sel-kind helixel--pending-sel) 'line))
      (when-let* ((fn (helixel--kind-flip-dir-fn 'line)))
        (helixel--sel-push (funcall fn helixel--pending-sel))))
    (let ((extending (and (region-active-p)
                          (eq helixel--raw-selection-type 'line))))
      (if extending
          ;; Extend/shrink in the stored direction.
          (let ((dir (helixel-sel-line-dir helixel--pending-sel)))
            (dotimes (_ abs-n)
              (helixel--extend-line-in-dir dir)))
        ;; New selection (forward: point at bottom, mark at top).
        (unless (helixel-replaying-p)
          (helixel--switch-state 'visual))
        (beginning-of-line)
        (push-mark-command t t)
        (end-of-line)
        (dotimes (_ (1- abs-n))
          (forward-line 1)
          (end-of-line)))
      (setq helixel--raw-selection-type 'line)
      (let* ((new-count (if extending
                            (max 1 (1+ (- (line-number-at-pos (region-end))
                                          (line-number-at-pos
                                           (region-beginning)))))
                          abs-n))
             (dir (if extending
                      (helixel-sel-line-dir helixel--pending-sel)
                    'forward)))
      (helixel--push-selection 'line `(:count ,new-count :dir ,dir)
                               #'helixel--recreate-line
                               (if (> new-count 1)
                                   (format "Lx%d" new-count)
                                 "L")
                               :advance #'helixel--repeat-advance-line)))))

(helixel-define-command helixel-select-line-up
    (:category movement :subcat lineselect
               :params (&optional count) :clear-highlights nil)
  (interactive "p")
  (let* ((n (or count 1))
         (abs-n (abs n))
         (flip-p (< n 0))
         (current-prefix-arg nil))
    ;; Flip permanent direction on negative prefix (like `N' for search).
    (when (and flip-p helixel--pending-sel
               (eq (helixel-sel-kind helixel--pending-sel) 'line))
      (when-let* ((fn (helixel--kind-flip-dir-fn 'line)))
        (helixel--sel-push (funcall fn helixel--pending-sel))))
    (let ((extending (and (region-active-p)
                          (eq helixel--raw-selection-type 'line))))
      (if extending
          ;; Extend/shrink in the stored direction.
          (let ((dir (helixel-sel-line-dir helixel--pending-sel)))
            (dotimes (_ abs-n)
              (helixel--extend-line-in-dir dir)))
        ;; New selection (backward: point at top, mark at bottom).
        (unless (helixel-replaying-p)
          (helixel--switch-state 'visual))
        (end-of-line)
        (push-mark-command t t)
        (beginning-of-line)
        (dotimes (_ (1- abs-n))
          (forward-line -1)
          (beginning-of-line)))
      (setq helixel--raw-selection-type 'line)
      (let* ((new-count (if extending
                            (max 1 (1+ (- (line-number-at-pos (region-end))
                                          (line-number-at-pos
                                           (region-beginning)))))
                          abs-n))
             (dir (if extending
                      (helixel-sel-line-dir helixel--pending-sel)
                    'backward)))
      (helixel--push-selection 'line `(:count ,new-count :dir ,dir)
                               #'helixel--recreate-line
                               (if (> new-count 1)
                                   (format "L^x%d" new-count)
                                 "L^")
                               :advance #'helixel--repeat-advance-line)))))

(helixel-define-command helixel-select-rectangle
    (:category movement :subcat rectselect
               :params (&optional count) :clear-highlights nil)
  (interactive "p")
  (let ((n (or count 1))
        (extending rectangle-mark-mode)
        (current-prefix-arg nil))
    (if extending
        (dotimes (_ n)
          (if (or (> (point) (mark))
                  (and (= (point) (mark))
                       (eq last-command 'helixel-select-rectangle)))
              (forward-line 1)
            (forward-line -1))
          (rectangle--reset-point-crutches))
      (helixel--switch-state 'visual)
      (push-mark (point) t t)
      (rectangle-mark-mode 1)
      (dotimes (_ (1- n))
        (forward-line 1)
        (rectangle--reset-point-crutches)))
    (setq helixel--raw-selection-type 'rect)
    (let* ((prev-count (helixel-sel-count helixel--pending-sel))
           (new-count (if extending (+ prev-count n) n)))
      (helixel--push-selection 'rect `(:count ,new-count)
                               #'helixel--recreate-rect
                               (if (> new-count 1)
                                   (format "rx%d" new-count)
                                 "r")
                               :advance #'helixel--repeat-advance-line))))


;; ── Line / Rect recreate functions ──
;; Used by `.` replay to rebuild linewise/rectangular selections.

(defun helixel--recreate-line (ctx)
  "Replay a linewise selection from CTX.
When :entry-kind is present (insert ops), position cursor
at the appropriate offset on the selected line:
  :entry-kind insert \=`region-beginning' + cursor-offset
  :entry-kind append \=`region-end' + cursor-offset
When :span is set, extends region back to the pre-recreate origin."
  (let ((n (helixel-sel-line-count ctx))
        (entry-kind (plist-get ctx :entry-kind)))
    (helixel--with-span ctx
      (if (eq (helixel-sel-line-dir ctx) 'backward)
          (helixel-select-line-up n)
        (helixel-select-line n))
      ;; Signal error when buffer is empty (nothing to select).
      ;; The strategy catches this to stop iteration.
      (when (and (bobp) (eobp))
        (user-error "No more targets")))
    (when entry-kind
      ;; Position cursor for key/text insertion.
      ;; Use region-beginning/region-end because helixel-select-line
      ;; leaves point on the LAST selected line, so
      ;; line-beginning-position/line-end-position would target
      ;; the wrong line for multi-line selections.
      (if (eq entry-kind 'append)
          (goto-char (region-end))
        (let ((rend (region-end)))
          (goto-char (region-beginning))
          ;; If point landed on the mark (zero-length region),
          ;; restore the visible region so the selection highlight
          ;; shows the full target range.
          (when (= (point) (mark))
            (set-mark rend))))
      (let ((off (helixel-sel-insert-cursor-offset ctx)))
        (when off (forward-char off))))))

(defun helixel--recreate-rect (ctx)
  "Replay a rectangular selection from CTX.
When :span is set, extends region back to the pre-recreate origin
without disturbing the rectangle's own mark.

NOTE: Does NOT use `helixel--with-span' because `push-mark' inside
`rectangle-mark-mode' behaves differently — we must deactivate the
rectangle mark, push the span origin, then reactivate.  The macro's
simple `push-mark' would interact poorly with the rect-mode mark."
  (let ((n (helixel-sel-rect-count ctx))
        (span-origin (when (plist-get ctx :span) (point))))
    (unless rectangle-mark-mode
      (helixel--switch-state 'visual)
      (push-mark (point) t t)
      (rectangle-mark-mode 1))
    (dotimes (_ (1- n))
      (forward-line 1)
      (rectangle--reset-point-crutches))
    (when span-origin
      (deactivate-mark)
      (push-mark span-origin t t)
      (activate-mark))
    (setq helixel--raw-selection-type 'rect)))

(defun helixel--recreate-movement (ctx)
  "Replay movement selection from CTX.
By default, the region accumulates across all commands (visual-mode
behaviour for e.g. `v w w d .`).  When :normal-mode is non-nil in
CTX, each movement resets the selection (normal-mode behaviour).
When :span is set (from `;' push), `normal-mode' is ignored so
\=`; d .' replays the full movement span correctly.
Signals `user-error' when point does not move (no more targets)."
  ;; :span forces visual-mode accumulation regardless of :normal-mode.
  (unless (and (helixel-sel-movement-normal-mode-p ctx)
               (not (plist-get ctx :span)))
    (setq helixel--current-state 'visual))
  (helixel--with-span ctx
    (let ((saved-pos (point)))
      (dolist (m (reverse (helixel-sel-movement-moves ctx)))
        (dotimes (_ (cdr m))
          (funcall (car m))))
      (when (= (point) saved-pos)
        (user-error "No more targets")))))


;; ── Line and movement advance functions (from helixel-repeat.el) ──

(defun helixel--repeat-advance-line (tx)
  "Advance TX past the current line target in selection's direction.
For append entry-kind (cursor at `region-end' after op), advance 1 line.
Otherwise advance by the selection count.
After advancing, recreates the line selection to position point
correctly (bol for insert, eol for append).  Returns nil at buffer edge.
Deactivates any prior region so `helixel-select-line-up' starts
fresh rather than extending a stale mark."
  (let* ((sel (helixel-edit-sel tx))
         (dir (if (eq (helixel-sel-line-dir sel) 'backward) -1 1))
         (entry-kind (plist-get (helixel-sel-ctx sel) :entry-kind))
         (count (if (eq entry-kind 'append) 1
                  (helixel-sel-line-count sel)))
         (lines-left count))
    (while (and (> lines-left 0) (= (forward-line dir) 0))
      (unless (helixel--blank-line-p)
        (setq lines-left (1- lines-left))))
    (when (= lines-left 0)
      (deactivate-mark)
      (helixel--recreate-selection sel)
      t)))

(defun helixel--repeat-advance-movement (tx)
  "Advance to next target for TX's movement selection.
Calls the selection's recreate function from the current cursor
position.  The recreate IS the advance (inline — movement commands
inherently create the region).  Returns t on success, nil when
point does not move.
The strategy skips the separate `recreate-selection' call for inline
advance functions to avoid double-moving."
  (let ((sel (helixel-edit-sel tx)))
    (when sel
      (condition-case nil
          (progn (helixel--recreate-selection sel) t)
        (error nil)))))

;; ── Kind registrations ──

(helixel-register-kind line
  :ctx-schema '(:required (:count :dir) :optional (:entry-kind :span))
  :recreate #'helixel--recreate-line
  :advance  #'helixel--repeat-advance-line
  :all-buffer-fn #'helixel--all-buffer-line
  :all-dir-fn #'helixel--all-dir-line
  :flip-dir-fn (lambda (sel)
                 (helixel-sel-update-ctx
                  sel :dir (helixel--flip-dir
                            (helixel-sel-line-dir sel))))
  :display  "L")

(helixel-register-kind rect
  :ctx-schema '(:required (:count) :optional ())
  :recreate #'helixel--recreate-rect
  :advance  nil
  :display  "R")

(helixel-register-kind movement
  :ctx-schema '(:required (:moves) :optional (:inline-advance :normal-mode))
  :recreate #'helixel--recreate-movement
  :advance  #'helixel--repeat-advance-movement
  :display  (lambda (ctx)
              (let ((ms (helixel-sel-movement-moves ctx)))
                (let ((n (apply #'+ (mapcar #'cdr ms))))
                  (format "v%d" n)))))

;; ── Visual move tracking (from helixel-state.el) ──

(defun helixel--track-visual-move (cmd)
  "Append movement CMD to `helixel--pending-sel'.
Creates/updates a `helixel-sel' struct of kind `movement' whenever
a region is active — from visual mode or `normal-mode' movements that
created a selection (e.g. w, e, b).
No-op during dot-repeat replay, or when no region is active."
  (when (and (not (helixel-replaying-p))
             (use-region-p))
    (let* ((ctx helixel--pending-sel)
           (entry (cons cmd 1)))
      (cond
       ;; Update: extend existing movement sel.
       ((and ctx (eq (helixel-sel-kind ctx) 'movement))
        (let* ((moves (helixel-sel-movement-moves ctx))
               (last (car moves)))
          (if (and last (eq (car last) cmd))
              (setcdr last (1+ (cdr last)))
            (helixel--sel-push
             (helixel-sel-update-ctx ctx :moves
                                     (cons entry moves))))))
       ;; Create: first movement that made a region.
       ;; Only when no sel exists — never clobber line/rect/textobj.
       ((null ctx)
        (helixel--sel-push
         (helixel-sel-create 'movement
                             `(:moves (,entry) :inline-advance t
                                      :normal-mode
                                      ,(eq helixel--current-state
                                           'normal))
                             #'helixel--recreate-movement
                             (lambda (c)
                               (let ((ms (helixel-sel-movement-moves c)))
                                 (let ((n (apply #'+ (mapcar #'cdr ms))))
                                   (format "v%d" n))))
                             :advance #'helixel--repeat-advance-movement)))))))

(provide 'helixel-move)
;;; helixel-move.el ends here
