#!/usr/bin/env -S emacs --batch --script
;;; gen-depgraph.el --- Generate dependency graph for helixel-mode -*- lexical-binding: t; -*-

;;; Commentary:
;;
;; Scan every helixel-*.el file in the project root and emit a
;; Mermaid `graph TD` block listing each file's compile-time
;; \(`require') edges to other helixel files.
;;
;; Usage (from project root):
;;
;;     emacs --batch -Q --script scripts/gen-depgraph.el > docs/DEPGRAPH.md
;;
;; The Makefile target `make depgraph' wires this up.

;;; Code:

(require 'cl-lib)

(defun helixel-depgraph--default-directory ()
  "Find the project root (containing helixel.el)."
  (let ((here (file-name-directory
               (or load-file-name buffer-file-name default-directory))))
    (expand-file-name ".." here)))

(defun helixel-depgraph--files ()
  "Return absolute paths of all helixel-*.el files in the project."
  (let ((root (helixel-depgraph--default-directory)))
    (sort (directory-files root t "\\`helixel.*\\.el\\'") #'string<)))

(defun helixel-depgraph--module-name (path)
  "Return module name (sans .el) for absolute PATH."
  (file-name-sans-extension (file-name-nondirectory path)))

(defun helixel-depgraph--requires (path)
  "Return list of helixel modules `require'd by file PATH."
  (let ((reqs nil))
    (with-temp-buffer
      (insert-file-contents path)
      (goto-char (point-min))
      (while (re-search-forward
              "^(require '\\(helixel[^) \t\n]*\\))" nil t)
        (push (match-string 1) reqs)))
    (nreverse (delete-dups reqs))))

(defun helixel-depgraph-emit ()
  "Print a Mermaid dependency graph to stdout."
  (princ "# helixel-mode dependency graph\n\n")
  (princ "Auto-generated by `scripts/gen-depgraph.el`.\n")
  (princ "Do not edit by hand; run `make depgraph' to refresh.\n\n")
  (princ "```mermaid\n")
  (princ "graph TD\n")
  (dolist (file (helixel-depgraph--files))
    (let ((mod (helixel-depgraph--module-name file)))
      (dolist (req (helixel-depgraph--requires file))
        (princ (format "  %s --> %s\n" mod req)))))
  (princ "```\n"))

(helixel-depgraph-emit)

;;; gen-depgraph.el ends here
